In [1]:
import pandas as pd

In [2]:
#load both dataframes

finish_df = pd.read_csv('finish_times.csv')
master_df = pd.read_csv('../data/ufc-master.csv')

In [3]:
display(finish_df)
display(master_df)

             R_fighter        B_fighter  round  time        date
0           Tito Ortiz     Ken Shamrock    1.0  2:23  10/10/2006
1        Kendall Grove      Chris Price    1.0  3:59  10/10/2006
2      Jason MacDonald        Ed Herman    1.0  2:43  10/10/2006
3          Matt Hamill  Seth Petruzelli    3.0  5:00  10/10/2006
4       Nate Marquardt  Crafton Wallace    2.0  1:14  10/10/2006
...                ...              ...    ...   ...         ...
11347   Cale Yarbrough      Tim Credeur    1.0  1:54   7/19/2008
11348    Brodie Farber     Rory Markham    1.0  1:37   7/19/2008
11349      Johnny Rees    Nate Loughran    1.0  4:21   7/19/2008
11350      James Giboo   Brad Blackburn    2.0  2:29   7/19/2008
11351       Dale Hartt  Shannon Gugerty    1.0  3:33   7/19/2008

[11352 rows x 5 columns]

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_Middleweight_rank,B_Welterweight_rank,B_Lightweight_rank,B_Featherweight_rank,B_Bantamweight_rank,B_Flyweight_rank,B_Pound-for-Pound_rank,better_rank,finish,finish_details
0,Deiveson Figueiredo,Joseph Benavidez,-225,180,44.444444,180.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,Red,SUB,Rear Naked Choke
1,Jack Hermansson,Kelvin Gastelum,-112,-112,89.285714,89.285714,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,7.0,NaN,NaN,NaN,NaN,NaN,NaN,Red,SUB,Heel Hook
2,Marc Diakiese,Rafael Fiziev,-167,135,59.880240,135.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN
3,Ariane Lipski,Luana Carolina,-125,100,80.000000,100.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,SUB,Kneebar
4,Alexandre Pantoja,Askar Askarov,-210,165,47.619048,165.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4287,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,KO/TKO,NaN
4288,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,KO/TKO,Punch
4289,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,KO/TKO,Punches
4290,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN
4291,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,3/21/2010,"Broomfield, Colorado, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN

In [4]:
merge_df = pd.merge(master_df, finish_df, how='left') #Does this really work??? Seems like magic.

#We need to double the finish_times csv to make this work.  We need to flip the blue and red fighters....

In [5]:
display(merge_df)

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_Lightweight_rank,B_Featherweight_rank,B_Bantamweight_rank,B_Flyweight_rank,B_Pound-for-Pound_rank,better_rank,finish,finish_details,round,time
0,Deiveson Figueiredo,Joseph Benavidez,-225,180,44.444444,180.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,2.0,NaN,Red,SUB,Rear Naked Choke,NaN,NaN
1,Jack Hermansson,Kelvin Gastelum,-112,-112,89.285714,89.285714,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,Red,SUB,Heel Hook,NaN,NaN
2,Marc Diakiese,Rafael Fiziev,-167,135,59.880240,135.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN,NaN,NaN
3,Ariane Lipski,Luana Carolina,-125,100,80.000000,100.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,neither,SUB,Kneebar,NaN,NaN
4,Alexandre Pantoja,Askar Askarov,-210,165,47.619048,165.000000,7/18/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4287,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,neither,KO/TKO,NaN,1.0,0:44
4288,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,neither,KO/TKO,Punch,1.0,2:01
4289,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,neither,KO/TKO,Punches,1.0,0:47
4290,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,3/21/2010,"Broomfield, Colorado, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN,3.0,5:00
4291,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,3/21/2010,"Broomfield, Colorado, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,neither,U-DEC,NaN,3.0,5:00

In [6]:
merge_df.to_csv('temp.csv', index=False)