In [1]:
import pandas as pd
import numpy as np
from functions import *
import random
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier

remove_fight_island = False

In [2]:
#Load models
#REMINDER: We are going to need to use 'eval' to get the models usable
with open('models.csv', newline='') as f:
    reader = csv.reader(f)
    models = list(reader)
    
print(len(models))


###SELECT MODEL TO OPTIMIZE
model_num = 4

5

In [3]:
models

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_06_13_20',
  'model_06_20_20',
  'model_6_27_20',
  'model_7_18_20',
  'model_7_25_20',
  'model_9_2_20',
  'model_9_10_20',
  'model_10_23_20',
  'model_10_27_20',
  'model_10_28_20'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(criterion='entropy', max_depth=10, max_leaf_nodes=336,\n                       min_samples_leaf=0.01, random_state=75,\n                       splitter='random')",
  "RandomForestClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,\n                       min_samples_leaf=0.009999000000000001, n_estimators=39,\n                       n_jobs=-1, random_state=75)",
  "GradientBoostingClassifier(max_depth=17, max_features='sqrt',\n                           max_leaf_nodes=316, min_samples_leaf=0.1,\n                           n_estimators=195, random_state=75)",
  'GaussianNB()',
  'LogisticRegression(max_iter=50000, random_state=75, tol=5.993308915320019)',
  'GaussianNB()',
  'GaussianNB()',
  'GradientBoostingClassifier(n_estimators=122, random_state=75)',
  'GaussianNB()',
  'GaussianNB(var_smoothing=1e-12)',
  'GaussianNB(var_smoothing=1e-12)',
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=6, n_estimators=195,\n                           random_state=75)',
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=197,\n                       n_jobs=-1, random_state=75)",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)"],
 ["['B_Middleweight_rank', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'gender', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'age_dif', 'B_ev', 'empty_arena']",
  "['R_odds', 'location', 'empty_arena']",
  "['country', 'B_ev', 'R_Height_cms', 'B_odds', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']",
  "['R_total_rounds_fought', 'B_total_rounds_fought', 'B_win_by_Decision_Unanimous', 'R_Stance', 'B_Height_cms', 'B_avg_SIG_STR_landed', 'age_dif', 'B_Stance', 'B_odds', 'location', 'empty_arena']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_win_by_Decision_Majority', 'B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'R_odds', 'R_current_lose_streak', 'R_Reach_cms', 'B_draw', 'total_round_dif', 'R_ev', 'B_ev']",
  "['R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_current_win_streak', 'R_win_by_Submission', 'B_win_by_Decision_Unanimous', 'R_win_by_Decision_Unanimous', 'R_current_lose_streak', 'B_win_by_TKO_Doctor_Stoppage', 'win_dif', 'B_win_by_Decision_Split', 'B_wins', 'R_Stance', 'B_age', 'B_Weight_lbs', 'R_ev', 'B_total_rounds_fought', 'location', 'R_odds', 'R_Reach_cms', 'R_Weight_lbs', 'R_current_win_streak', 'R_age', 'empty_arena', 'R_win_by_Decision_Split', 'R_draw', 'lose_streak_dif', 'B_draw']",
  "['R_Reach_cms', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'ko_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['win_streak_dif', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['B_Weight_lbs', 'B_Flyweight_rank', 'B_avg_TD_landed', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']",
  '[\'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']'],
 ['0', '7', '2', '0', '0', '0', '0', '0', '0', '1', '3', '2', '27', '1', '5'],
 ['536.4236082',
  '345.1147018',
  '355.7009476',
  '-774.4056181',
  '1867.371334',
  '1770.977716',
  '221.4512891',
  '1867.371334',
  '-200.6168769',
  '27.45559206',
  '245.9650841',
  '221.1165991',
  '690.5773086',
  '339.6609304',
  '-54.76505768']]

In [4]:
df = pd.read_csv("../data/kaggle_data/ufc-master.csv")

In [5]:
#Let's put all the labels in a dataframe
df['label'] = ''
#If the winner is not Red or Blue we can remove it.
mask = df['Winner'] == 'Red'
df['label'][mask] = 0
mask = df['Winner'] == 'Blue'
df['label'][mask] = 1

#df["Winner"] = df["Winner"].astype('category')
df = df[(df['Winner'] == 'Blue') | (df['Winner'] == 'Red')]


#Make sure lable is numeric
df['label'] = pd.to_numeric(df['label'], errors='coerce')

<ipython-input-5-7548c2416a5f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'][mask] = 0
<ipython-input-5-7548c2416a5f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'][mask] = 1

In [6]:
#Let's fix the date
df['date'] = pd.to_datetime(df['date'])

In [7]:
#Create a label df:
label_df = df['label']

#Let's create an odds df too:
odds_df = df[['R_odds', 'B_odds']]

In [8]:
#Split the test set.  We are always(?) going to use the last 200 matches as the test set, so we don't want those around
#as we pick models

df_train = df[250:]
odds_train = odds_df[250:]
label_train = label_df[250:]

df_test = df[:250]
odds_test = odds_df[:250]
label_test = label_df[:250]

print(len(df_test))
print(len(odds_test))
print(len(label_test))

print(len(df_train))
print(len(odds_train))
print(len(label_train))

250
250
250
4509
4509
4509

In [9]:
if remove_fight_island:
    ##Let's remove the Fight island contests and see how that affects score
    df_test_no_fight_island = df_test[(df_test['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_train_no_fight_island = df_train[(df_train['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_test = df_test_no_fight_island
    df_train = df_train_no_fight_island



print(len(df_test))
print(len(df_train))

250
4509

In [10]:
display(df_train)
display(df_test)

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
250,Junior Dos Santos,Ciryl Gane,325,-400,325.000000,25.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
251,Cub Swanson,Daniel Pineda,132,-152,132.000000,65.789474,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
252,Renato Moicano,Rafael Fiziev,120,-140,120.000000,71.428571,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
253,Gavin Tucker,Billy Quarantillo,165,-190,165.000000,52.631579,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
254,Tecia Torres,Sam Hughes,-550,425,18.181818,425.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4754,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,2.0,0.00,0.5,0.0,0.0,0.0,0.0,0.0,0.0,1
4755,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,1.00,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0
4756,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,2.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4757,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,0.0,0.60,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0
4758,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,6.0,0.66,0.5,1.0,1.0,1.0,6.0,1.0,1.0,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Chan Sung Jung,Dan Ige,130,-162,130.000000,61.728395,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Aleksei Oleinik,Serghei Spivac,200,-265,200.000000,37.735849,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Marlon Vera,Davey Grant,-230,180,43.478261,180.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Julian Erosa,SeungWoo Choi,120,-150,120.000000,66.666667,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Wellington Turman,Bruno Silva,100,-125,100.000000,80.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Jimmy Flick,Cody Durden,-157,137,63.694268,137.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
246,Christos Giagos,Carlton Minus,-345,285,28.985507,285.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
247,Tony Ferguson,Charles Oliveira,-185,160,54.054054,160.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
248,Mackenzie Dern,Virna Jandiroba,-160,140,62.500000,140.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
249,Kevin Holland,Jacare Souza,-135,115,74.074074,115.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [11]:
#Set a value for the nulls in the ranks

weightclass_list = ['B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank']
df_train[weightclass_list] = df_train[weightclass_list].fillna(17)
df_test[weightclass_list] = df_test[weightclass_list].fillna(17)

C:\Users\matth\anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [12]:
df_test
#df_test.to_csv('test.csv')

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Chan Sung Jung,Dan Ige,130,-162,130.000000,61.728395,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Aleksei Oleinik,Serghei Spivac,200,-265,200.000000,37.735849,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Marlon Vera,Davey Grant,-230,180,43.478261,180.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Julian Erosa,SeungWoo Choi,120,-150,120.000000,66.666667,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Wellington Turman,Bruno Silva,100,-125,100.000000,80.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Jimmy Flick,Cody Durden,-157,137,63.694268,137.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
246,Christos Giagos,Carlton Minus,-345,285,28.985507,285.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
247,Tony Ferguson,Charles Oliveira,-185,160,54.054054,160.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
248,Mackenzie Dern,Virna Jandiroba,-160,140,62.500000,140.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
249,Kevin Holland,Jacare Souza,-135,115,74.074074,115.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
#1. Set features
#2. Set Hyperparameters
#3. Set EV
#4. Remove Features

In [14]:
models[1][model_num]

'GaussianNB()'

In [15]:
test_model_name = models[0][model_num]
test_model = eval(models[1][model_num])
test_model_features = eval(models[2][model_num])
test_model_ev = eval(models[3][model_num])

In [16]:
old_test_model = test_model
old_test_model_features = test_model_features
old_test_model_ev = test_model_ev

In [17]:
print(df_test.columns.tolist()) #Keeps us from truncating

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'R_kd_bout', 'B_kd_bout', 'R_sig_str_landed_bout', 'B_sig_str_landed_bout', 'R_sig_str_attempted_bout', 'B_sig_str_attempted_bout', 'R_sig_str_pct_bout', 'B_sig_str_pct_bout', 'R_tot_str_landed_bout', 'B_tot_str_landed_bout', 'R_tot_str_attempted_bout', 'B_tot_str_attempted_bout', 'R_td_landed_bout', 'B_td_landed_bout', 'R_td_attempted_bout', 'B_td_attempted_bout', 'R_td_pct_bout', 'B_td_pct_bout', 'R_sub_attempts_bout', 'B_sub_attempts_bout', 'R_pass_bout', 'B_pass_bout', 'R_rev_bout', 'B_rev_bout', 'label']

In [18]:
#1. set features
my_pos_features = ['R_odds', 'B_odds', 'R_ev', 'B_ev',
       'location', 'country', 'title_bout', 'weight_class', 'gender',
       'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak',
       'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT',
       'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses',
       'B_total_rounds_fought', 'B_total_title_bouts',
       'B_win_by_Decision_Majority', 'B_win_by_Decision_Split',
       'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission',
       'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms',
       'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak',
       'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed',
       'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct',
       'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought',
       'R_total_title_bouts', 'R_win_by_Decision_Majority',
       'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous',
       'R_win_by_KO/TKO', 'R_win_by_Submission',
       'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms',
       'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif',
       'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif',
       'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif',
       'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif',
       'avg_td_dif', 'empty_arena', 'B_match_weightclass_rank', 'R_match_weightclass_rank', 
        "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank",
        "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 
        'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 
        'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", 
        "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 
        'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 
        'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 
        'B_Pound-for-Pound_rank', 'better_rank']

In [19]:
print(test_model_name)
print(test_model)
print(test_model_features)
print(test_model_ev)

model_4
GaussianNB()
['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

In [20]:
def save_model():
    score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)
    models[0][model_num] =  test_model_name 
    models[1][model_num] = test_model
    models[2][model_num] = test_model_features
    models[3][model_num] = test_model_ev
    models[4][model_num] = score    
    
    with open('models.csv', 'w', newline='') as outfile:
        writer = csv.writer(outfile)
        for row in models:
            print("HI")
            writer.writerow(row)

    outfile.close()

In [21]:
def print_model():
    print()
    print(test_model_name)
    print(test_model)
    print(test_model_features)
    print(test_model_ev)
    print()

In [22]:
keep_going = True
#keep_going = False
while(keep_going):
    #1. Set Features
    #get_best_features(pos_features, m, df, cur_features, labels, odds, scale=False)
    test_model_features = (get_best_features(my_pos_features, test_model, df_train, test_model_features, label_train, odds_train, 
                                             min_ev=test_model_ev))
    print_model()
    save_model()
    #2 Set hyperparameters
    #def tune_hyperparameters(input_model, input_features, input_df, input_labels, odds_input):
    test_model = tune_hyperparameters(test_model, test_model_features, df_train, label_train, odds_train, 
                                      min_ev=test_model_ev)
    print_model()
    save_model()
    #3. Set EV
    #def tune_ev(input_model, input_features, input_df, input_labels, odds_input, verbose=False):
    test_model_ev = tune_ev(test_model, test_model_features, df_train, label_train, odds_train, verbose=False)

    old_test_model_features = test_model_features #This prevents
                                                  #an uneccesary loop
    print_model()
    save_model()
    #4. Remove Features
    #def remove_to_improve(cur_features, m, df, labels, odds, scale=False, min_ev = 0):
    test_model_features = remove_to_improve(test_model_features, test_model, df_train, label_train, odds_train, min_ev = test_model_ev)    
    keep_going = False
    if old_test_model != test_model:
        print("The hyperparameters are different")
        print("OLD:")
        print(old_test_model)
        print("NEW:")
        print(test_model)
        keep_going = True
        old_test_model = test_model
    if old_test_model_features != test_model_features:
        print("The features are different")
        print("OLD:")
        print(old_test_model_features)
        print("NEW:")
        print(test_model_features)
        keep_going = True
        old_test_model_features = test_model_features
    if old_test_model_ev != test_model_ev:
        print("The EV is different")
        print("OLD:")
        print(old_test_model_ev)
        print("NEW:")
        print(test_model_ev)
        keep_going = True
        old_test_model_ev = test_model_ev
    print_model()
    save_model()

Current best score is: 10417.633942622451
Feature: B_avg_SIG_STR_pct Score: 10481.027880415735
Feature: B_losses Score: 11722.814304152258
Feature: B_Stance Score: 14676.677243571316
Feature: B_Lightweight_rank Score: 16868.614152613227
The best feature was B_Lightweight_rank.  It scored 16868.614152613227
Current best score is: 16868.614152613227
Feature: B_current_lose_streak Score: 17336.40909112966
Feature: B_longest_win_streak Score: 17980.214900191724
Feature: B_losses Score: 18805.318279093044
Feature: R_age Score: 19303.353813657315
The best feature was R_age.  It scored 19303.353813657315
Current best score is: 19303.353813657315
Feature: B_longest_win_streak Score: 19669.25971829601
Feature: R_avg_TD_pct Score: 21927.37174363342
The best feature was R_avg_TD_pct.  It scored 21927.37174363342
Current best score is: 21927.37174363342
Feature: B_current_lose_streak Score: 22074.64420454246
Feature: R_total_rounds_fought Score: 23259.62786424984
The best feature was R_total_rounds_fought.  It scored 23259.62786424984
Current best score is: 23259.62786424984
Feature: B_win_by_Decision_Unanimous Score: 23453.210591884545
The best feature was B_win_by_Decision_Unanimous.  It scored 23453.210591884545
Current best score is: 23453.210591884545
NO IMPROVEMENT
FINAL BEST SCORE: 23453.210591884545

model_4
GaussianNB()
['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

(3556, 23)

(3556,)

(3556, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0        130     -162  0.536646  0.463354       0
1        200     -265  0.496289  0.503711       1
2       -230      180  0.615920  0.384080       0
3        120     -150  0.461141  0.538859       1
4        100     -125  0.476100  0.523900       1
..       ...      ...       ...       ...     ...
245     -157      137  0.202560  0.797440       0
246     -345      285  0.870639  0.129361       0
247     -185      160  0.894885  0.105115       1
248     -160      140  0.661492  0.338508       0
249     -135      115  0.895199  0.104801       0

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 231
          Number of winning bets: 129
          Number of losing bets: 102
          Number of underdog bets: 102
          Number of underdog wins: 46
          Number of underdog losses: 56
          Number of Favorite bets: 125
          Number of favorite wins: 82
          Number of favorite losses: 43
          Number of even bets: 4
          Number of even wins: 1
          Number of even losses: 3
          Profit: 1103.751826527694
          Profit per bet: 4.778146435184823
          Profit per match: 4.415007306110776


HI
HI
HI
HI
HI


Starting New Run for GaussianNB


Previous Best Score: 23453.210591884545
var_smoothing: 1e-12 Score: 23423.21059188454
var_smoothing: 1e-11 Score: 23423.21059188454
var_smoothing: 1e-10 Score: 23423.21059188454
var_smoothing: 1e-09 Score: 23453.210591884545
var_smoothing: 1e-08 Score: 23412.606143562705
var_smoothing: 1e-07 Score: 19404.31284682797
var_smoothing: 1e-06 Score: 15148.800935011339

model_4
GaussianNB()
['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

(3556, 23)

(3556,)

(3556, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0        130     -162  0.536646  0.463354       0
1        200     -265  0.496289  0.503711       1
2       -230      180  0.615920  0.384080       0
3        120     -150  0.461141  0.538859       1
4        100     -125  0.476100  0.523900       1
..       ...      ...       ...       ...     ...
245     -157      137  0.202560  0.797440       0
246     -345      285  0.870639  0.129361       0
247     -185      160  0.894885  0.105115       1
248     -160      140  0.661492  0.338508       0
249     -135      115  0.895199  0.104801       0

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 231
          Number of winning bets: 129
          Number of losing bets: 102
          Number of underdog bets: 102
          Number of underdog wins: 46
          Number of underdog losses: 56
          Number of Favorite bets: 125
          Number of favorite wins: 82
          Number of favorite losses: 43
          Number of even bets: 4
          Number of even wins: 1
          Number of even losses: 3
          Profit: 1103.751826527694
          Profit per bet: 4.778146435184823
          Profit per match: 4.415007306110776


HI
HI
HI
HI
HI
0 23453.210591884545
1 22673.486262868322
2 22799.37755619034
3 22153.058579366323
4 21203.510997997633
5 21372.328227555547
6 20819.75817590734
7 20699.728470990933
8 20447.26612977103
9 19071.2879107128
10 20294.796048863624
11 19296.483517727615
12 18369.546415006975
13 17052.542217731792
14 16445.380864696454
15 15902.564732298704
16 15219.944223307713
17 14097.412125155497
18 14421.84042474382
19 13815.389582392683
20 13922.011159134443
21 14062.320844895446
22 13068.525838624348
23 13112.98251654959
24 12867.786193513643
25 12794.796628701391
26 14220.701842829458
27 14422.336637932154
28 15117.756019168115
29 14795.879711218808
30 14540.829318267217
31 13847.28397493286
32 12445.07640806614
33 12194.93389216199
34 11489.212361673062
35 11422.471366566253
36 11281.389058688279
37 11247.990507805143
38 11636.217317661198
39 10298.778321407332
40 9750.156471119364
41 9665.141290713673
42 9741.437173047161
43 10176.142296348262
44 10178.800045438235
45 10267.671260768933
46 9248.678569978147
47 8803.696220446309
48 8428.484859958233
49 8330.003213684595
50 7715.70011723379
51 8608.52180767184
52 8323.894182930118
53 8761.653744782237
54 8674.656098664233
55 8734.54846103366
56 8317.430578915779
57 8085.222764755632
58 8465.82437780508
59 8854.346558051398
60 8743.147612069843
61 8324.0698782095
62 8448.176796448493
63 8351.089238844806
64 7837.02895026839
65 7842.577785473712
66 8135.383168496486
67 8647.975761089077
68 8539.581672419128
69 7873.410212971807
70 8176.981641543234
71 8058.058564620158
72 8305.201421763015
73 8725.201421763015
74 8690.87093743253
75 7884.320994837812
76 6951.320994837812
77 6985.90341242023
78 7305.90341242023
79 7563.946890681099
80 7178.946890681099
81 6377.037799772008
82 6621.7997045339125
83 6589.605087556687
84 6844.605087556687
85 6304.605087556687
86 6330.692044078427
87 6252.826431430205
88 6397.826431430205
89 6472.826431430205
90 6767.826431430205
91 6721.917340521114
92 6872.577717879605
93 7142.577717879605
94 7402.577717879605
95 7008.238095238095
96 6977.0
97 6832.0
98 6492.0
99 6207.0
100 6112.0
101 6392.0
102 6592.0
103 6937.0
104 6623.0
105 6813.0
106 6234.0
107 6294.0
108 6334.0
109 6634.0
110 6494.0
111 6309.0
112 6809.0
113 6634.0
114 6509.0
115 6989.0
116 6914.0
117 6759.0
118 6934.0
119 6957.0
120 6682.0
121 6657.0
122 6632.0
123 6697.0
124 6427.0
125 6325.0
126 6105.0
127 5815.0
128 5775.0
129 5470.0
130 5210.0
131 5017.0
132 5217.0
133 5232.0
134 5082.0
135 4877.0
136 4650.0
137 4750.0
138 4593.0
139 4458.0
140 4713.0
141 4813.0
142 4838.0
143 4938.0
144 4893.0
145 4993.0
146 4923.0
147 4633.0
148 4358.0
149 4398.0
150 3748.0
151 3583.0
152 3583.0
153 3583.0
154 3518.0
155 3363.0
156 3463.0
157 3463.0
158 3305.0
159 3220.0
160 3150.0
161 3250.0
162 2920.0
163 2560.0
164 2490.0
165 2525.0
166 2625.0
167 2425.0
168 2250.0
169 2130.0
170 2330.0
171 2630.0
172 2730.0
173 2360.0
174 2065.0
175 1955.0
176 2055.0
177 2255.0
178 2455.0
179 2300.0
180 2320.0
181 2080.0
182 2180.0
183 2280.0
184 2045.0
185 2040.0
186 2240.0
187 2340.0
188 2440.0
189 2440.0
190 2235.0
191 1965.0
192 1965.0
193 1720.0
194 1215.0
195 1515.0
196 1515.0
197 1300.0
198 1300.0
199 1300.0

model_4
GaussianNB()
['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

(3556, 23)

(3556,)

(3556, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0        130     -162  0.536646  0.463354       0
1        200     -265  0.496289  0.503711       1
2       -230      180  0.615920  0.384080       0
3        120     -150  0.461141  0.538859       1
4        100     -125  0.476100  0.523900       1
..       ...      ...       ...       ...     ...
245     -157      137  0.202560  0.797440       0
246     -345      285  0.870639  0.129361       0
247     -185      160  0.894885  0.105115       1
248     -160      140  0.661492  0.338508       0
249     -135      115  0.895199  0.104801       0

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 231
          Number of winning bets: 129
          Number of losing bets: 102
          Number of underdog bets: 102
          Number of underdog wins: 46
          Number of underdog losses: 56
          Number of Favorite bets: 125
          Number of favorite wins: 82
          Number of favorite losses: 43
          Number of even bets: 4
          Number of even wins: 1
          Number of even losses: 3
          Profit: 1103.751826527694
          Profit per bet: 4.778146435184823
          Profit per match: 4.415007306110776


HI
HI
HI
HI
HI
The original score is 23453.210591884545
Score:  23259.62786424984
Score:  22023.06729729571
Score:  17405.24623763541
Score:  19735.683362772674
Score:  16696.885405118283
Score:  20482.25541979738
Score:  18638.52775456037
Score:  21773.836769648107
Score:  18794.82130445395
Score:  22917.900407247886
Score:  22502.72779289333
Score:  21956.201192938628
Score:  23418.92523736895
Score:  21164.89997140128
Score:  15394.407402824068
Score:  13862.889310772593
Score:  20220.879945548477
Score:  18470.385212256646
Score:  18805.64161540701
Score:  14199.46595046243
Score:  17725.40896434844
Score:  20709.9841380503
Score:  18742.414935565706

model_4
GaussianNB()
['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

(3556, 23)

(3556,)

(3556, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0        130     -162  0.536646  0.463354       0
1        200     -265  0.496289  0.503711       1
2       -230      180  0.615920  0.384080       0
3        120     -150  0.461141  0.538859       1
4        100     -125  0.476100  0.523900       1
..       ...      ...       ...       ...     ...
245     -157      137  0.202560  0.797440       0
246     -345      285  0.870639  0.129361       0
247     -185      160  0.894885  0.105115       1
248     -160      140  0.661492  0.338508       0
249     -135      115  0.895199  0.104801       0

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 231
          Number of winning bets: 129
          Number of losing bets: 102
          Number of underdog bets: 102
          Number of underdog wins: 46
          Number of underdog losses: 56
          Number of Favorite bets: 125
          Number of favorite wins: 82
          Number of favorite losses: 43
          Number of even bets: 4
          Number of even wins: 1
          Number of even losses: 3
          Profit: 1103.751826527694
          Profit per bet: 4.778146435184823
          Profit per match: 4.415007306110776


HI
HI
HI
HI
HI

In [23]:
#Get new score:
#def evaluate_model(input_model, input_features, input_ev, train_df, train_labels, train_odds, test_df, test_labels, test_odds, verbose=True):
score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)

(3556, 23)

(3556,)

(3556, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0        130     -162  0.536646  0.463354       0
1        200     -265  0.496289  0.503711       1
2       -230      180  0.615920  0.384080       0
3        120     -150  0.461141  0.538859       1
4        100     -125  0.476100  0.523900       1
..       ...      ...       ...       ...     ...
245     -157      137  0.202560  0.797440       0
246     -345      285  0.870639  0.129361       0
247     -185      160  0.894885  0.105115       1
248     -160      140  0.661492  0.338508       0
249     -135      115  0.895199  0.104801       0

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 231
          Number of winning bets: 129
          Number of losing bets: 102
          Number of underdog bets: 102
          Number of underdog wins: 46
          Number of underdog losses: 56
          Number of Favorite bets: 125
          Number of favorite wins: 82
          Number of favorite losses: 43
          Number of even bets: 4
          Number of even wins: 1
          Number of even losses: 3
          Profit: 1103.751826527694
          Profit per bet: 4.778146435184823
          Profit per match: 4.415007306110776

print(test_model_name) 
print(models[0][model_num])
print()
print(test_model)
print(eval(models[1][model_num]))
print()
print(test_model_features) 
print(eval(models[2][model_num]))
print()
print(test_model_ev)
print(eval(models[3][model_num]))

In [24]:
models[0][model_num] =  test_model_name 
models[1][model_num] = test_model
models[2][model_num] = test_model_features
models[3][model_num] = test_model_ev
models[4][model_num] = score

In [25]:
with open('models.csv', 'w', newline='') as outfile:
    writer = csv.writer(outfile)
    for row in models:
        print("HI")
        writer.writerow(row)
    
outfile.close()

HI
HI
HI
HI
HI

In [26]:
with open('models.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
    
print(len(data))

5

In [27]:
data

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_06_13_20',
  'model_06_20_20',
  'model_6_27_20',
  'model_7_18_20',
  'model_7_25_20',
  'model_9_2_20',
  'model_9_10_20',
  'model_10_23_20',
  'model_10_27_20',
  'model_10_28_20'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(criterion='entropy', max_depth=10, max_leaf_nodes=336,\n                       min_samples_leaf=0.01, random_state=75,\n                       splitter='random')",
  "RandomForestClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,\n                       min_samples_leaf=0.009999000000000001, n_estimators=39,\n                       n_jobs=-1, random_state=75)",
  "GradientBoostingClassifier(max_depth=17, max_features='sqrt',\n                           max_leaf_nodes=316, min_samples_leaf=0.1,\n                           n_estimators=195, random_state=75)",
  'GaussianNB()',
  'LogisticRegression(max_iter=50000, random_state=75, tol=5.993308915320019)',
  'GaussianNB()',
  'GaussianNB()',
  'GradientBoostingClassifier(n_estimators=122, random_state=75)',
  'GaussianNB()',
  'GaussianNB(var_smoothing=1e-12)',
  'GaussianNB(var_smoothing=1e-12)',
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=6, n_estimators=195,\n                           random_state=75)',
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=197,\n                       n_jobs=-1, random_state=75)",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)"],
 ["['B_Middleweight_rank', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'gender', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'age_dif', 'B_ev', 'empty_arena']",
  "['R_odds', 'location', 'empty_arena']",
  "['country', 'B_ev', 'R_Height_cms', 'B_odds', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']",
  "['R_total_rounds_fought', 'B_total_rounds_fought', 'B_win_by_Decision_Unanimous', 'R_Stance', 'B_Height_cms', 'B_avg_SIG_STR_landed', 'age_dif', 'B_Stance', 'B_odds', 'location', 'empty_arena']",
  "['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_win_by_Decision_Majority', 'B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'R_odds', 'R_current_lose_streak', 'R_Reach_cms', 'B_draw', 'total_round_dif', 'R_ev', 'B_ev']",
  "['R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_current_win_streak', 'R_win_by_Submission', 'B_win_by_Decision_Unanimous', 'R_win_by_Decision_Unanimous', 'R_current_lose_streak', 'B_win_by_TKO_Doctor_Stoppage', 'win_dif', 'B_win_by_Decision_Split', 'B_wins', 'R_Stance', 'B_age', 'B_Weight_lbs', 'R_ev', 'B_total_rounds_fought', 'location', 'R_odds', 'R_Reach_cms', 'R_Weight_lbs', 'R_current_win_streak', 'R_age', 'empty_arena', 'R_win_by_Decision_Split', 'R_draw', 'lose_streak_dif', 'B_draw']",
  "['R_Reach_cms', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'ko_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['win_streak_dif', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['B_Weight_lbs', 'B_Flyweight_rank', 'B_avg_TD_landed', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']",
  '[\'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']'],
 ['0', '7', '2', '0', '0', '0', '0', '0', '0', '1', '3', '2', '27', '1', '5'],
 ['536.4236082',
  '345.1147018',
  '355.7009476',
  '-774.4056181',
  '1103.751826527694',
  '1770.977716',
  '221.4512891',
  '1867.371334',
  '-200.6168769',
  '27.45559206',
  '245.9650841',
  '221.1165991',
  '690.5773086',
  '339.6609304',
  '-54.76505768']]