In [1]:
import pandas as pd
import numpy as np
from functions import *
import random
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier

remove_fight_island = False

In [2]:
#Load models
#REMINDER: We are going to need to use 'eval' to get the models usable
with open('models.csv', newline='') as f:
    reader = csv.reader(f)
    models = list(reader)
    
print(len(models))


###SELECT MODEL TO OPTIMIZE
model_num = 4

5

In [3]:
models

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_06_13_20',
  'model_06_20_20',
  'model_6_27_20',
  'model_7_18_20',
  'model_7_25_20',
  'model_9_2_20',
  'model_9_10_20',
  'model_10_23_20',
  'model_10_27_20',
  'model_10_28_20'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(max_depth=3, max_leaf_nodes=336, min_samples_leaf=0.01,\n                       random_state=75, splitter='random')",
  'RandomForestClassifier(max_depth=10, min_samples_leaf=0.0099, n_jobs=-1,\n                       random_state=75)',
  "GradientBoostingClassifier(max_depth=17, max_features='sqrt',\n                           max_leaf_nodes=316, min_samples_leaf=0.1,\n                           n_estimators=195, random_state=75)",
  'GaussianNB(var_smoothing=1e-08)',
  'LogisticRegression(max_iter=50000, random_state=75, tol=5.993308915320019)',
  'GaussianNB()',
  'GaussianNB()',
  'GradientBoostingClassifier(n_estimators=122, random_state=75)',
  'GaussianNB()',
  'GaussianNB(var_smoothing=1e-12)',
  'GaussianNB(var_smoothing=1e-12)',
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=6, n_estimators=195,\n                           random_state=75)',
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=197,\n                       n_jobs=-1, random_state=75)",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)"],
 ["['sig_str_dif', 'R_Weight_lbs', 'B_Weight_lbs', 'R_Lightweight_rank', 'R_draw', 'R_Light Heavyweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']",
  '["B_Women\'s Featherweight_rank", \'B_avg_SIG_STR_landed\', \'R_odds\', \'gender\', \'R_ev\', \'total_round_dif\']',
  "['R_Reach_cms', 'B_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev', 'total_round_dif']",
  "['B_total_title_bouts', 'B_Weight_lbs', 'B_avg_TD_pct', 'R_current_lose_streak', 'B_avg_SIG_STR_pct', 'R_Stance', 'R_win_by_Decision_Unanimous', 'B_age', 'B_avg_SUB_ATT', 'reach_dif', 'country', 'R_odds']",
  "['total_round_dif']",
  "['B_win_by_Decision_Majority', 'B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'R_odds', 'R_current_lose_streak', 'R_Reach_cms', 'B_draw', 'total_round_dif', 'R_ev', 'B_ev']",
  "['R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_current_win_streak', 'R_win_by_Submission', 'B_win_by_Decision_Unanimous', 'R_win_by_Decision_Unanimous', 'R_current_lose_streak', 'B_win_by_TKO_Doctor_Stoppage', 'win_dif', 'B_win_by_Decision_Split', 'B_wins', 'R_Stance', 'B_age', 'B_Weight_lbs', 'R_ev', 'B_total_rounds_fought', 'location', 'R_odds', 'R_Reach_cms', 'R_Weight_lbs', 'R_current_win_streak', 'R_age', 'empty_arena', 'R_win_by_Decision_Split', 'R_draw', 'lose_streak_dif', 'B_draw']",
  "['R_Reach_cms', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'ko_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['win_streak_dif', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['B_Weight_lbs', 'B_Flyweight_rank', 'B_avg_TD_landed', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']",
  '[\'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']'],
 ['0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '3', '2', '27', '1', '5'],
 ['538.4166865',
  '-324.7349695106435',
  '-949.3347427574704',
  '1205.0828045280437',
  '-100000',
  '1165.977716',
  '528.6527731',
  '1500.93994',
  '493.1647765',
  '-431.4817089',
  '-35.23037836',
  '-19.43318131',
  '290.9104159',
  '-91.0629001',
  '-1129.80692']]

In [4]:
df = pd.read_csv("../data/ufc-master.csv")

In [5]:
#Let's put all the labels in a dataframe
df['label'] = ''
#If the winner is not Red or Blue we can remove it.
mask = df['Winner'] == 'Red'
df['label'][mask] = 0
mask = df['Winner'] == 'Blue'
df['label'][mask] = 1

#df["Winner"] = df["Winner"].astype('category')
df = df[(df['Winner'] == 'Blue') | (df['Winner'] == 'Red')]


#Make sure lable is numeric
df['label'] = pd.to_numeric(df['label'], errors='coerce')

<ipython-input-5-7548c2416a5f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'][mask] = 0
<ipython-input-5-7548c2416a5f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'][mask] = 1

In [6]:
#Let's fix the date
df['date'] = pd.to_datetime(df['date'])

In [7]:
#Create a label df:
label_df = df['label']

#Let's create an odds df too:
odds_df = df[['R_odds', 'B_odds']]

In [8]:
#Split the test set.  We are always(?) going to use the last 200 matches as the test set, so we don't want those around
#as we pick models

df_train = df[200:]
odds_train = odds_df[200:]
label_train = label_df[200:]

df_test = df[:200]
odds_test = odds_df[:200]
label_test = label_df[:200]

print(len(df_test))
print(len(odds_test))
print(len(label_test))

print(len(df_train))
print(len(odds_train))
print(len(label_train))

200
200
200
4533
4533
4533

In [9]:
if remove_fight_island:
    ##Let's remove the Fight island contests and see how that affects score
    df_test_no_fight_island = df_test[(df_test['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_train_no_fight_island = df_train[(df_train['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_test = df_test_no_fight_island
    df_train = df_train_no_fight_island



print(len(df_test))
print(len(df_train))

200
4533

In [10]:
display(df_train)
display(df_test)

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
200,Carlos Condit,Matt Brown,-177,145,56.497175,145.000000,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
201,Santiago Ponzinibbio,Li Jingliang,-305,240,32.786885,240.000000,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
202,Joaquin Buckley,Alessio Di Chirico,-278,215,35.971223,215.000000,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
203,Punahele Soriano,Dusko Todorovic,130,-159,130.000000,62.893082,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
204,Wu Yanan,Joselyne Edwards,-110,-110,90.909091,90.909091,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4728,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,2.0,0.00,0.5,0.0,0.0,0.0,0.0,0.0,0.0,1
4729,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,1.00,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0
4730,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,2.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4731,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,0.0,0.60,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0
4732,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,6.0,0.66,0.5,1.0,1.0,1.0,6.0,1.0,1.0,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Jairzinho Rozenstruik,Augusto Sakai,-118,-106,84.745763,94.339623,2021-06-05,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Walt Harris,Marcin Tybura,140,-177,140.000000,56.497175,2021-06-05,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Roman Dolidze,Laureano Staropoli,-150,120,66.666667,120.000000,2021-06-05,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Santiago Ponzinibbio,Miguel Baeza,105,-134,105.000000,74.626866,2021-06-05,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Dusko Todorovic,Gregory Rodrigues,-177,140,56.497175,140.000000,2021-06-05,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Francisco Figueiredo,Jerome Rivera,-155,125,64.516129,125.000000,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
196,Mike Davis,Mason Jones,-175,135,57.142857,135.000000,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
197,Umar Nurmagomedov,Sergey Morozov,-530,375,18.867925,375.000000,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
198,Victoria Leonardo,Manon Fiorot,170,-215,170.000000,46.511628,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
199,Max Holloway,Calvin Kattar,-162,138,61.728395,138.000000,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [11]:
#Set a value for the nulls in the ranks

weightclass_list = ['B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank']
df_train[weightclass_list] = df_train[weightclass_list].fillna(17)
df_test[weightclass_list] = df_test[weightclass_list].fillna(17)

C:\Users\matth\anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [12]:
df_test
#df_test.to_csv('test.csv')

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Jairzinho Rozenstruik,Augusto Sakai,-118,-106,84.745763,94.339623,2021-06-05,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Walt Harris,Marcin Tybura,140,-177,140.000000,56.497175,2021-06-05,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Roman Dolidze,Laureano Staropoli,-150,120,66.666667,120.000000,2021-06-05,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Santiago Ponzinibbio,Miguel Baeza,105,-134,105.000000,74.626866,2021-06-05,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Dusko Todorovic,Gregory Rodrigues,-177,140,56.497175,140.000000,2021-06-05,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Francisco Figueiredo,Jerome Rivera,-155,125,64.516129,125.000000,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
196,Mike Davis,Mason Jones,-175,135,57.142857,135.000000,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
197,Umar Nurmagomedov,Sergey Morozov,-530,375,18.867925,375.000000,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
198,Victoria Leonardo,Manon Fiorot,170,-215,170.000000,46.511628,2021-01-20,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
199,Max Holloway,Calvin Kattar,-162,138,61.728395,138.000000,2021-01-16,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
#1. Set features
#2. Set Hyperparameters
#3. Set EV
#4. Remove Features

In [14]:
models[1][model_num]

'GaussianNB(var_smoothing=1e-08)'

In [15]:
test_model_name = models[0][model_num]
test_model = eval(models[1][model_num])
test_model_features = eval(models[2][model_num])
test_model_ev = eval(models[3][model_num])

In [16]:
old_test_model = test_model
old_test_model_features = test_model_features
old_test_model_ev = test_model_ev

In [17]:
print(df_test.columns.tolist()) #Keeps us from truncating

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'R_kd_bout', 'B_kd_bout', 'R_sig_str_landed_bout', 'B_sig_str_landed_bout', 'R_sig_str_attempted_bout', 'B_sig_str_attempted_bout', 'R_sig_str_pct_bout', 'B_sig_str_pct_bout', 'R_tot_str_landed_bout', 'B_tot_str_landed_bout', 'R_tot_str_attempted_bout', 'B_tot_str_attempted_bout', 'R_td_landed_bout', 'B_td_landed_bout', 'R_td_attempted_bout', 'B_td_attempted_bout', 'R_td_pct_bout', 'B_td_pct_bout', 'R_sub_attempts_bout', 'B_sub_attempts_bout', 'R_pass_bout', 'B_pass_bout', 'R_rev_bout', 'B_rev_bout', 'label']

In [18]:
#1. set features
my_pos_features = ['R_odds', 'B_odds', 'R_ev', 'B_ev',
       'location', 'country', 'title_bout', 'weight_class', 'gender',
       'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak',
       'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT',
       'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses',
       'B_total_rounds_fought', 'B_total_title_bouts',
       'B_win_by_Decision_Majority', 'B_win_by_Decision_Split',
       'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission',
       'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms',
       'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak',
       'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed',
       'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct',
       'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought',
       'R_total_title_bouts', 'R_win_by_Decision_Majority',
       'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous',
       'R_win_by_KO/TKO', 'R_win_by_Submission',
       'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms',
       'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif',
       'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif',
       'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif',
       'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif',
       'avg_td_dif', 'empty_arena', 'B_match_weightclass_rank', 'R_match_weightclass_rank', 
        "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank",
        "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 
        'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 
        'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", 
        "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 
        'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 
        'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 
        'B_Pound-for-Pound_rank', 'better_rank']

In [19]:
print(test_model_name)
print(test_model)
print(test_model_features)
print(test_model_ev)

model_4
GaussianNB(var_smoothing=1e-08)
['total_round_dif']
0

In [20]:
def save_model():
    score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)
    models[0][model_num] =  test_model_name 
    models[1][model_num] = test_model
    models[2][model_num] = test_model_features
    models[3][model_num] = test_model_ev
    models[4][model_num] = score    
    
    with open('models.csv', 'w', newline='') as outfile:
        writer = csv.writer(outfile)
        for row in models:
            print("HI")
            writer.writerow(row)

    outfile.close()

In [21]:
def print_model():
    print()
    print(test_model_name)
    print(test_model)
    print(test_model_features)
    print(test_model_ev)
    print()

In [22]:
keep_going = True
#keep_going = False
while(keep_going):
    #1. Set Features
    #get_best_features(pos_features, m, df, cur_features, labels, odds, scale=False)
    test_model_features = (get_best_features(my_pos_features, test_model, df_train, test_model_features, label_train, odds_train, 
                                             min_ev=test_model_ev))
    print_model()
    save_model()
    #2 Set hyperparameters
    #def tune_hyperparameters(input_model, input_features, input_df, input_labels, odds_input):
    test_model = tune_hyperparameters(test_model, test_model_features, df_train, label_train, odds_train, 
                                      min_ev=test_model_ev)
    print_model()
    save_model()
    #3. Set EV
    #def tune_ev(input_model, input_features, input_df, input_labels, odds_input, verbose=False):
    test_model_ev = tune_ev(test_model, test_model_features, df_train, label_train, odds_train, verbose=False)

    old_test_model_features = test_model_features #This prevents
                                                  #an uneccesary loop
    print_model()
    save_model()
    #4. Remove Features
    #def remove_to_improve(cur_features, m, df, labels, odds, scale=False, min_ev = 0):
    test_model_features = remove_to_improve(test_model_features, test_model, df_train, label_train, odds_train, min_ev = test_model_ev)    
    keep_going = False
    if old_test_model != test_model:
        print("The hyperparameters are different")
        print("OLD:")
        print(old_test_model)
        print("NEW:")
        print(test_model)
        keep_going = True
        old_test_model = test_model
    if old_test_model_features != test_model_features:
        print("The features are different")
        print("OLD:")
        print(old_test_model_features)
        print("NEW:")
        print(test_model_features)
        keep_going = True
        old_test_model_features = test_model_features
    if old_test_model_ev != test_model_ev:
        print("The EV is different")
        print("OLD:")
        print(old_test_model_ev)
        print("NEW:")
        print(test_model_ev)
        keep_going = True
        old_test_model_ev = test_model_ev
    print_model()
    save_model()

Current best score is: -14661.886414302215
Feature: B_ev Score: -12428.402174820452
Feature: country Score: -5587.590660384954
Feature: B_avg_SIG_STR_landed Score: -4188.552862525437
Feature: B_Stance Score: 5363.948681728758
The best feature was B_Stance.  It scored 5363.948681728758
Current best score is: 5363.948681728758
Feature: B_current_lose_streak Score: 5605.5210716009115
Feature: B_avg_SIG_STR_pct Score: 7331.8079549408185
Feature: B_Lightweight_rank Score: 8200.895483298544
The best feature was B_Lightweight_rank.  It scored 8200.895483298544
Current best score is: 8200.895483298544
Feature: title_bout Score: 8480.587700000035
Feature: B_avg_SIG_STR_pct Score: 11742.370819567599
Feature: R_avg_TD_landed Score: 12085.632798565375
The best feature was R_avg_TD_landed.  It scored 12085.632798565375
Current best score is: 12085.632798565375
Feature: B_current_win_streak Score: 13536.556213929858
Feature: B_draw Score: 13613.561691107796
The best feature was B_draw.  It scored 13613.561691107796
Current best score is: 13613.561691107796
Feature: B_current_win_streak Score: 13798.161875534039
Feature: win_dif Score: 13923.160686055415
Feature: sig_str_dif Score: 14419.420075402235
The best feature was sig_str_dif.  It scored 14419.420075402235
Current best score is: 14419.420075402235
Feature: B_win_by_Decision_Unanimous Score: 15019.426728933271
The best feature was B_win_by_Decision_Unanimous.  It scored 15019.426728933271
Current best score is: 15019.426728933271
Feature: B_Pound-for-Pound_rank Score: 15197.566323258688
The best feature was B_Pound-for-Pound_rank.  It scored 15197.566323258688
Current best score is: 15197.566323258688
Feature: B_win_by_Submission Score: 15674.769468216738
The best feature was B_win_by_Submission.  It scored 15674.769468216738
Current best score is: 15674.769468216738
Feature: empty_arena Score: 15684.479376429148
The best feature was empty_arena.  It scored 15684.479376429148
Current best score is: 15684.479376429148
Feature: B_wins Score: 16319.093148496017
The best feature was B_wins.  It scored 16319.093148496017
Current best score is: 16319.093148496017
Feature: R_avg_SUB_ATT Score: 16603.90823540064
Feature: avg_sub_att_dif Score: 17945.30967486637
The best feature was avg_sub_att_dif.  It scored 17945.30967486637
Current best score is: 17945.30967486637
Feature: B_current_win_streak Score: 18849.66954121005
The best feature was B_current_win_streak.  It scored 18849.66954121005
Current best score is: 18849.66954121005
Feature: B_win_by_Decision_Majority Score: 20071.512192846585
The best feature was B_win_by_Decision_Majority.  It scored 20071.512192846585
Current best score is: 20071.512192846585
NO IMPROVEMENT
FINAL BEST SCORE: 20071.512192846585

model_4
GaussianNB(var_smoothing=1e-08)
['B_win_by_Decision_Majority', 'B_current_win_streak', 'avg_sub_att_dif', 'B_wins', 'empty_arena', 'B_win_by_Submission', 'B_Pound-for-Pound_rank', 'B_win_by_Decision_Unanimous', 'sig_str_dif', 'B_draw', 'R_avg_TD_landed', 'B_Lightweight_rank', 'B_Stance', 'total_round_dif']
0

(4176, 17)

(4176,)

(4176, 2)

(198, 17)

(198,)

(198, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -118     -106  0.946686  0.053314       0
1        140     -177  0.907238  0.092762       1
2       -150      120  0.976852  0.023148       0
3        105     -134  0.885362  0.114638       0
4       -177      140  0.943454  0.056546       1
..       ...      ...       ...       ...     ...
193     -155      125  0.939295  0.060705       0
194     -175      135  0.943698  0.056302       1
195     -530      375  0.947120  0.052880       0
196      170     -215  0.988726  0.011274       1
197     -162      138  0.965063  0.034937       0

[198 rows x 5 columns]

          Number of matches: 198
          Number of bets: 198
          Number of winning bets: 109
          Number of losing bets: 89
          Number of underdog bets: 85
          Number of underdog wins: 38
          Number of underdog losses: 47
          Number of Favorite bets: 111
          Number of favorite wins: 71
          Number of favorite losses: 40
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 79.82596213788835
          Profit per bet: 0.40316142493883006
          Profit per match: 0.40316142493883006


HI
HI
HI
HI
HI


Starting New Run for GaussianNB


Previous Best Score: 20071.512192846585
var_smoothing: 1e-12 Score: 13510.661622317297
var_smoothing: 1e-11 Score: 14630.213637349003
var_smoothing: 1e-10 Score: 16029.943513713913
var_smoothing: 1e-09 Score: 16340.657905919677
var_smoothing: 1e-08 Score: 20071.512192846585
var_smoothing: 1e-07 Score: 10553.01000330261
var_smoothing: 1e-06 Score: -2767.848820532736

model_4
GaussianNB(var_smoothing=1e-08)
['B_win_by_Decision_Majority', 'B_current_win_streak', 'avg_sub_att_dif', 'B_wins', 'empty_arena', 'B_win_by_Submission', 'B_Pound-for-Pound_rank', 'B_win_by_Decision_Unanimous', 'sig_str_dif', 'B_draw', 'R_avg_TD_landed', 'B_Lightweight_rank', 'B_Stance', 'total_round_dif']
0

(4176, 17)

(4176,)

(4176, 2)

(198, 17)

(198,)

(198, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -118     -106  0.946686  0.053314       0
1        140     -177  0.907238  0.092762       1
2       -150      120  0.976852  0.023148       0
3        105     -134  0.885362  0.114638       0
4       -177      140  0.943454  0.056546       1
..       ...      ...       ...       ...     ...
193     -155      125  0.939295  0.060705       0
194     -175      135  0.943698  0.056302       1
195     -530      375  0.947120  0.052880       0
196      170     -215  0.988726  0.011274       1
197     -162      138  0.965063  0.034937       0

[198 rows x 5 columns]

          Number of matches: 198
          Number of bets: 198
          Number of winning bets: 109
          Number of losing bets: 89
          Number of underdog bets: 85
          Number of underdog wins: 38
          Number of underdog losses: 47
          Number of Favorite bets: 111
          Number of favorite wins: 71
          Number of favorite losses: 40
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 79.82596213788835
          Profit per bet: 0.40316142493883006
          Profit per match: 0.40316142493883006


HI
HI
HI
HI
HI
0 20071.512192846585
1 19292.65787996034
2 19285.359789603775
3 18598.755156843552
4 18452.271775649253
5 17768.235429615477
6 17384.408579136474
7 17178.238907591614
8 16752.792530512055
9 16761.327230779756
10 16574.095282808667
11 15980.564813283043
12 15727.696618331307
13 15224.896366737346
14 14419.792193469088
15 14592.703012767282
16 14535.415742465553
17 14133.632600804991
18 13834.8195596809
19 13484.891699873639
20 12607.44022954643
21 12648.02031068934
22 12435.794729977091
23 11917.837993299565
24 11595.206594062489
25 11999.659283710738
26 11984.84126349319
27 11618.065409176521
28 11531.162638953072
29 10892.521031286535
30 10164.83798907706
31 10374.609934327471
32 9739.951424879191
33 9727.008086573698
34 8887.437281152064
35 8978.335921614573
36 8127.339289236525
37 7883.334310220558
38 8845.131199903379
39 8526.306273446875
40 9171.116106222726
41 8873.946806225485
42 8832.51486928214
43 9216.374537673048
44 9488.412426562727
45 9753.011996749285
46 10352.75189931565
47 10072.712721501255
48 9357.074454438573
49 10140.082782589052
50 10476.471874822864
51 10640.713502327755
52 11288.530876160796
53 10943.282618931908
54 12523.57278251541
55 12677.50395044067
56 13004.035139539908
57 13015.357080277865
58 12539.866096415066
59 12792.797627681142
60 14169.685467425195
61 14480.045732957873
62 14586.180804576816
63 14631.236779103574
64 14577.514716926842
65 14795.241559310169
66 14974.371994092779
67 14609.82404069954
68 14057.613951937725
69 14486.51455482777
70 14638.480213270663
71 15163.103673546293
72 14205.00462929971
73 14250.605909073605
74 13413.622602525082
75 12484.2353231378
76 12235.748118341271
77 12279.680562708498
78 12074.682338710272
79 11510.098111343437
80 11554.332065794782
81 11912.470593933309
82 11725.414316877032
83 11798.790940253655
84 11347.591007500325
85 10990.578020487339
86 11518.716548625867
87 11926.760026886737
88 11471.283836410546
89 10406.045741172453
90 10194.064526668302
91 10803.15543575921
92 11157.8158131177
93 10833.238095238095
94 11708.238095238095
95 11413.0
96 11573.0
97 12123.0
98 11171.0
99 10655.0
100 9582.0
101 9520.0
102 8459.0
103 7744.0
104 7439.0
105 7174.0
106 7104.0
107 7372.0
108 7446.0
109 7886.0
110 7538.0
111 7933.0
112 7891.0
113 7483.0
114 7967.0
115 9287.0
116 9432.0
117 8727.0
118 8947.0
119 7562.0
120 7001.0
121 6841.0
122 7096.0
123 7514.0
124 7439.0
125 7534.0
126 7669.0
127 7625.0
128 7715.0
129 7150.0
130 6985.0
131 7350.0
132 6945.0
133 7290.0
134 7755.0
135 7545.0
136 7280.0
137 7740.0
138 7305.0
139 7430.0
140 7520.0
141 7258.0
142 7193.0
143 7733.0
144 7535.0
145 7260.0
146 6855.0
147 7475.0
148 7440.0
149 7170.0
150 7292.0
151 7087.0
152 6795.0
153 6958.0
154 6944.0
155 7604.0
156 7402.0
157 6666.0
158 6488.0
159 6723.0
160 6238.0
161 5968.0
162 6198.0
163 6343.0
164 5843.0
165 5143.0
166 4973.0
167 4033.0
168 3718.0
169 4118.0
170 4718.0
171 4408.0
172 4508.0
173 5033.0
174 5333.0
175 5478.0
176 6278.0
177 6478.0
178 6098.0
179 5523.0
180 5638.0
181 5733.0
182 6233.0
183 6223.0
184 6193.0
185 6363.0
186 6168.0
187 6173.0
188 6168.0
189 6248.0
190 6348.0
191 6433.0
192 6013.0
193 6213.0
194 6158.0
195 6358.0
196 6133.0
197 5753.0
198 5358.0
199 5328.0

model_4
GaussianNB(var_smoothing=1e-08)
['B_win_by_Decision_Majority', 'B_current_win_streak', 'avg_sub_att_dif', 'B_wins', 'empty_arena', 'B_win_by_Submission', 'B_Pound-for-Pound_rank', 'B_win_by_Decision_Unanimous', 'sig_str_dif', 'B_draw', 'R_avg_TD_landed', 'B_Lightweight_rank', 'B_Stance', 'total_round_dif']
0

(4176, 17)

(4176,)

(4176, 2)

(198, 17)

(198,)

(198, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -118     -106  0.946686  0.053314       0
1        140     -177  0.907238  0.092762       1
2       -150      120  0.976852  0.023148       0
3        105     -134  0.885362  0.114638       0
4       -177      140  0.943454  0.056546       1
..       ...      ...       ...       ...     ...
193     -155      125  0.939295  0.060705       0
194     -175      135  0.943698  0.056302       1
195     -530      375  0.947120  0.052880       0
196      170     -215  0.988726  0.011274       1
197     -162      138  0.965063  0.034937       0

[198 rows x 5 columns]

          Number of matches: 198
          Number of bets: 198
          Number of winning bets: 109
          Number of losing bets: 89
          Number of underdog bets: 85
          Number of underdog wins: 38
          Number of underdog losses: 47
          Number of Favorite bets: 111
          Number of favorite wins: 71
          Number of favorite losses: 40
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 79.82596213788835
          Profit per bet: 0.40316142493883006
          Profit per match: 0.40316142493883006


HI
HI
HI
HI
HI
The original score is 20071.512192846585
Score:  18849.66954121005
Score:  16063.238239109105
Score:  16807.261447006404
Score:  18541.131959807302
Score:  18502.469896185856
Score:  18628.518678903114
Score:  18028.970523989123
Score:  19722.590272888585
Score:  16206.44846266555
Score:  14912.903985271903
Score:  6931.639412953464
Score:  11858.298113772002
Score:  -6441.747028951872
Score:  18552.168717870387

model_4
GaussianNB(var_smoothing=1e-08)
['B_win_by_Decision_Majority', 'B_current_win_streak', 'avg_sub_att_dif', 'B_wins', 'empty_arena', 'B_win_by_Submission', 'B_Pound-for-Pound_rank', 'B_win_by_Decision_Unanimous', 'sig_str_dif', 'B_draw', 'R_avg_TD_landed', 'B_Lightweight_rank', 'B_Stance', 'total_round_dif']
0

(4176, 17)

(4176,)

(4176, 2)

(198, 17)

(198,)

(198, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -118     -106  0.946686  0.053314       0
1        140     -177  0.907238  0.092762       1
2       -150      120  0.976852  0.023148       0
3        105     -134  0.885362  0.114638       0
4       -177      140  0.943454  0.056546       1
..       ...      ...       ...       ...     ...
193     -155      125  0.939295  0.060705       0
194     -175      135  0.943698  0.056302       1
195     -530      375  0.947120  0.052880       0
196      170     -215  0.988726  0.011274       1
197     -162      138  0.965063  0.034937       0

[198 rows x 5 columns]

          Number of matches: 198
          Number of bets: 198
          Number of winning bets: 109
          Number of losing bets: 89
          Number of underdog bets: 85
          Number of underdog wins: 38
          Number of underdog losses: 47
          Number of Favorite bets: 111
          Number of favorite wins: 71
          Number of favorite losses: 40
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 79.82596213788835
          Profit per bet: 0.40316142493883006
          Profit per match: 0.40316142493883006


HI
HI
HI
HI
HI

In [23]:
#Get new score:
#def evaluate_model(input_model, input_features, input_ev, train_df, train_labels, train_odds, test_df, test_labels, test_odds, verbose=True):
score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)

(4176, 17)

(4176,)

(4176, 2)

(198, 17)

(198,)

(198, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -118     -106  0.946686  0.053314       0
1        140     -177  0.907238  0.092762       1
2       -150      120  0.976852  0.023148       0
3        105     -134  0.885362  0.114638       0
4       -177      140  0.943454  0.056546       1
..       ...      ...       ...       ...     ...
193     -155      125  0.939295  0.060705       0
194     -175      135  0.943698  0.056302       1
195     -530      375  0.947120  0.052880       0
196      170     -215  0.988726  0.011274       1
197     -162      138  0.965063  0.034937       0

[198 rows x 5 columns]

          Number of matches: 198
          Number of bets: 198
          Number of winning bets: 109
          Number of losing bets: 89
          Number of underdog bets: 85
          Number of underdog wins: 38
          Number of underdog losses: 47
          Number of Favorite bets: 111
          Number of favorite wins: 71
          Number of favorite losses: 40
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 79.82596213788835
          Profit per bet: 0.40316142493883006
          Profit per match: 0.40316142493883006

print(test_model_name) 
print(models[0][model_num])
print()
print(test_model)
print(eval(models[1][model_num]))
print()
print(test_model_features) 
print(eval(models[2][model_num]))
print()
print(test_model_ev)
print(eval(models[3][model_num]))

In [24]:
models[0][model_num] =  test_model_name 
models[1][model_num] = test_model
models[2][model_num] = test_model_features
models[3][model_num] = test_model_ev
models[4][model_num] = score

In [25]:
with open('models.csv', 'w', newline='') as outfile:
    writer = csv.writer(outfile)
    for row in models:
        print("HI")
        writer.writerow(row)
    
outfile.close()

HI
HI
HI
HI
HI

In [26]:
with open('models.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
    
print(len(data))

5

In [27]:
data

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_06_13_20',
  'model_06_20_20',
  'model_6_27_20',
  'model_7_18_20',
  'model_7_25_20',
  'model_9_2_20',
  'model_9_10_20',
  'model_10_23_20',
  'model_10_27_20',
  'model_10_28_20'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(max_depth=3, max_leaf_nodes=336, min_samples_leaf=0.01,\n                       random_state=75, splitter='random')",
  'RandomForestClassifier(max_depth=10, min_samples_leaf=0.0099, n_jobs=-1,\n                       random_state=75)',
  "GradientBoostingClassifier(max_depth=17, max_features='sqrt',\n                           max_leaf_nodes=316, min_samples_leaf=0.1,\n                           n_estimators=195, random_state=75)",
  'GaussianNB(var_smoothing=1e-08)',
  'LogisticRegression(max_iter=50000, random_state=75, tol=5.993308915320019)',
  'GaussianNB()',
  'GaussianNB()',
  'GradientBoostingClassifier(n_estimators=122, random_state=75)',
  'GaussianNB()',
  'GaussianNB(var_smoothing=1e-12)',
  'GaussianNB(var_smoothing=1e-12)',
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=6, n_estimators=195,\n                           random_state=75)',
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=197,\n                       n_jobs=-1, random_state=75)",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)"],
 ["['sig_str_dif', 'R_Weight_lbs', 'B_Weight_lbs', 'R_Lightweight_rank', 'R_draw', 'R_Light Heavyweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']",
  '["B_Women\'s Featherweight_rank", \'B_avg_SIG_STR_landed\', \'R_odds\', \'gender\', \'R_ev\', \'total_round_dif\']',
  "['R_Reach_cms', 'B_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev', 'total_round_dif']",
  "['B_total_title_bouts', 'B_Weight_lbs', 'B_avg_TD_pct', 'R_current_lose_streak', 'B_avg_SIG_STR_pct', 'R_Stance', 'R_win_by_Decision_Unanimous', 'B_age', 'B_avg_SUB_ATT', 'reach_dif', 'country', 'R_odds']",
  "['B_win_by_Decision_Majority', 'B_current_win_streak', 'avg_sub_att_dif', 'B_wins', 'empty_arena', 'B_win_by_Submission', 'B_Pound-for-Pound_rank', 'B_win_by_Decision_Unanimous', 'sig_str_dif', 'B_draw', 'R_avg_TD_landed', 'B_Lightweight_rank', 'B_Stance', 'total_round_dif']",
  "['B_win_by_Decision_Majority', 'B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'R_odds', 'R_current_lose_streak', 'R_Reach_cms', 'B_draw', 'total_round_dif', 'R_ev', 'B_ev']",
  "['R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_current_win_streak', 'R_win_by_Submission', 'B_win_by_Decision_Unanimous', 'R_win_by_Decision_Unanimous', 'R_current_lose_streak', 'B_win_by_TKO_Doctor_Stoppage', 'win_dif', 'B_win_by_Decision_Split', 'B_wins', 'R_Stance', 'B_age', 'B_Weight_lbs', 'R_ev', 'B_total_rounds_fought', 'location', 'R_odds', 'R_Reach_cms', 'R_Weight_lbs', 'R_current_win_streak', 'R_age', 'empty_arena', 'R_win_by_Decision_Split', 'R_draw', 'lose_streak_dif', 'B_draw']",
  "['R_Reach_cms', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'ko_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['win_streak_dif', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['B_Weight_lbs', 'B_Flyweight_rank', 'B_avg_TD_landed', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']",
  '[\'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']'],
 ['0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '3', '2', '27', '1', '5'],
 ['538.4166865',
  '-324.7349695106435',
  '-949.3347427574704',
  '1205.0828045280437',
  '79.82596213788835',
  '1165.977716',
  '528.6527731',
  '1500.93994',
  '493.1647765',
  '-431.4817089',
  '-35.23037836',
  '-19.43318131',
  '290.9104159',
  '-91.0629001',
  '-1129.80692']]