In [1]:
import pandas as pd
import numpy as np
from functions import *
import random
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import RadiusNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier

remove_fight_island = False

In [2]:
#Load models
#REMINDER: We are going to need to use 'eval' to get the models usable
with open('../data/models.csv', newline='') as f:
    reader = csv.reader(f)
    models = list(reader)
    
print(len(models))


###SELECT MODEL TO OPTIMIZE
model_num = 10

5

In [3]:
models

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_5',
  'model_6',
  'model_7',
  'model_8',
  'model_9',
  'model_10'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(criterion='entropy', max_depth=10, max_leaf_nodes=336,\n                       min_samples_leaf=0.01, random_state=75,\n                       splitter='random')",
  "RandomForestClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,\n                       min_samples_leaf=0.009999000000000001, n_estimators=140,\n                       n_jobs=-1, random_state=75)",
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=0.0015,\n                           n_estimators=195, random_state=75)',
  'GaussianNB()',
  "ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,\n                    min_samples_leaf=0.009999000000000001, random_state=75)",
  'MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)',
  "RadiusNeighborsClassifier(outlier_label='most_frequent')",
  'KNeighborsClassifier()',
  "SGDClassifier(loss='modified_huber', random_state=75)",
  'GaussianProcessClassifier(random_state=75)'],
 ["['R_age', 'R_draw', 'B_losses', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'age_dif', 'B_ev', 'empty_arena']",
  "['weight_class', 'R_odds', 'location', 'empty_arena']",
  "['no_of_rounds', 'B_draw', 'country', 'B_ev', 'R_Height_cms', 'B_odds', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']",
  '["R_Women\'s Featherweight_rank", \'B_Featherweight_rank\', \'B_win_by_KO/TKO\', \'R_Pound-for-Pound_rank\', \'reach_dif\', "R_Women\'s Bantamweight_rank", \'age_dif\', \'weight_class\', \'B_Reach_cms\', \'B_Welterweight_rank\', \'B_total_title_bouts\', \'R_avg_TD_pct\', \'B_Bantamweight_rank\', \'R_Featherweight_rank\', \'no_of_rounds\', \'B_draw\', \'B_Stance\', \'R_win_by_TKO_Doctor_Stoppage\', \'R_current_win_streak\', \'B_avg_SIG_STR_landed\', \'country\']',
  "['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_ev', 'B_avg_TD_landed']",
  "['R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'B_ev']",
  '[\'R_draw\', \'B_Lightweight_rank\', \'R_Lightweight_rank\', "R_Women\'s Strawweight_rank", \'B_Flyweight_rank\', \'B_draw\', \'R_win_by_Decision_Majority\', \'R_Flyweight_rank\', \'height_dif\', \'B_total_title_bouts\', \'B_Bantamweight_rank\', \'total_title_bout_dif\', \'R_longest_win_streak\', \'R_avg_TD_landed\', \'B_avg_SIG_STR_landed\']',
  "['R_win_by_KO/TKO']",
  '["B_Women\'s Strawweight_rank", \'R_avg_TD_pct\', \'B_ev\']',
  '[]'],
 ['0', '0', '0', '33', '0', '6', '1', '1', '1', '0', '0'],
 ['756.4408141',
  '454.1692746',
  '-290.9255036',
  '2770.653314',
  '1103.751827',
  '-223.1757086',
  '927.5219432',
  '895.4540868',
  '-1524.7893',
  '2083.539134',
  '-10000']]

In [4]:
df = pd.read_csv("../data/kaggle_data/ufc-master.csv")

In [5]:
#Let's put all the labels in a dataframe
df['label'] = ''
#If the winner is not Red or Blue we can remove it.
mask = df['Winner'] == 'Red'
df['label'][mask] = 0
mask = df['Winner'] == 'Blue'
df['label'][mask] = 1

#df["Winner"] = df["Winner"].astype('category')
df = df[(df['Winner'] == 'Blue') | (df['Winner'] == 'Red')]


#Make sure lable is numeric
df['label'] = pd.to_numeric(df['label'], errors='coerce')

<ipython-input-5-7548c2416a5f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'][mask] = 0
<ipython-input-5-7548c2416a5f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'][mask] = 1

In [6]:
#Let's fix the date
df['date'] = pd.to_datetime(df['date'])

In [7]:
#Create a label df:
label_df = df['label']

#Let's create an odds df too:
odds_df = df[['R_odds', 'B_odds']]

In [8]:
#Split the test set.  We are always(?) going to use the last 200 matches as the test set, so we don't want those around
#as we pick models

df_train = df[250:]
odds_train = odds_df[250:]
label_train = label_df[250:]

df_test = df[:250]
odds_test = odds_df[:250]
label_test = label_df[:250]

print(len(df_test))
print(len(odds_test))
print(len(label_test))

print(len(df_train))
print(len(odds_train))
print(len(label_train))

250
250
250
4509
4509
4509

In [9]:
if remove_fight_island:
    ##Let's remove the Fight island contests and see how that affects score
    df_test_no_fight_island = df_test[(df_test['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_train_no_fight_island = df_train[(df_train['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_test = df_test_no_fight_island
    df_train = df_train_no_fight_island



print(len(df_test))
print(len(df_train))

250
4509

In [10]:
display(df_train)
display(df_test)

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
250,Junior Dos Santos,Ciryl Gane,325,-400,325.000000,25.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
251,Cub Swanson,Daniel Pineda,132,-152,132.000000,65.789474,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
252,Renato Moicano,Rafael Fiziev,120,-140,120.000000,71.428571,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
253,Gavin Tucker,Billy Quarantillo,165,-190,165.000000,52.631579,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
254,Tecia Torres,Sam Hughes,-550,425,18.181818,425.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4754,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,2.0,0.00,0.5,0.0,0.0,0.0,0.0,0.0,0.0,1
4755,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,1.00,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0
4756,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,2.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4757,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,0.0,0.60,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0
4758,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,6.0,0.66,0.5,1.0,1.0,1.0,6.0,1.0,1.0,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Chan Sung Jung,Dan Ige,130,-162,130.000000,61.728395,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Aleksei Oleinik,Serghei Spivac,200,-265,200.000000,37.735849,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Marlon Vera,Davey Grant,-230,180,43.478261,180.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Julian Erosa,SeungWoo Choi,120,-150,120.000000,66.666667,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Wellington Turman,Bruno Silva,100,-125,100.000000,80.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Jimmy Flick,Cody Durden,-157,137,63.694268,137.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
246,Christos Giagos,Carlton Minus,-345,285,28.985507,285.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
247,Tony Ferguson,Charles Oliveira,-185,160,54.054054,160.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
248,Mackenzie Dern,Virna Jandiroba,-160,140,62.500000,140.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
249,Kevin Holland,Jacare Souza,-135,115,74.074074,115.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [11]:
#Set a value for the nulls in the ranks

weightclass_list = ['B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank']
df_train[weightclass_list] = df_train[weightclass_list].fillna(17)
df_test[weightclass_list] = df_test[weightclass_list].fillna(17)

C:\Users\matth\anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [12]:
df_test
#df_test.to_csv('test.csv')

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Chan Sung Jung,Dan Ige,130,-162,130.000000,61.728395,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Aleksei Oleinik,Serghei Spivac,200,-265,200.000000,37.735849,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Marlon Vera,Davey Grant,-230,180,43.478261,180.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Julian Erosa,SeungWoo Choi,120,-150,120.000000,66.666667,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Wellington Turman,Bruno Silva,100,-125,100.000000,80.000000,2021-06-19,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Jimmy Flick,Cody Durden,-157,137,63.694268,137.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
246,Christos Giagos,Carlton Minus,-345,285,28.985507,285.000000,2020-12-19,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
247,Tony Ferguson,Charles Oliveira,-185,160,54.054054,160.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
248,Mackenzie Dern,Virna Jandiroba,-160,140,62.500000,140.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
249,Kevin Holland,Jacare Souza,-135,115,74.074074,115.000000,2020-12-12,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
#1. Set features
#2. Set Hyperparameters
#3. Set EV
#4. Remove Features

In [14]:
models[1][model_num]

'GaussianProcessClassifier(random_state=75)'

In [15]:
test_model_name = models[0][model_num]
test_model = eval(models[1][model_num])
test_model_features = eval(models[2][model_num])
test_model_ev = eval(models[3][model_num])

In [16]:
old_test_model = test_model
old_test_model_features = test_model_features
old_test_model_ev = test_model_ev

In [17]:
print(df_test.columns.tolist()) #Keeps us from truncating

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'R_kd_bout', 'B_kd_bout', 'R_sig_str_landed_bout', 'B_sig_str_landed_bout', 'R_sig_str_attempted_bout', 'B_sig_str_attempted_bout', 'R_sig_str_pct_bout', 'B_sig_str_pct_bout', 'R_tot_str_landed_bout', 'B_tot_str_landed_bout', 'R_tot_str_attempted_bout', 'B_tot_str_attempted_bout', 'R_td_landed_bout', 'B_td_landed_bout', 'R_td_attempted_bout', 'B_td_attempted_bout', 'R_td_pct_bout', 'B_td_pct_bout', 'R_sub_attempts_bout', 'B_sub_attempts_bout', 'R_pass_bout', 'B_pass_bout', 'R_rev_bout', 'B_rev_bout', 'label']

In [18]:
#1. set features
my_pos_features = ['R_odds', 'B_odds', 'R_ev', 'B_ev',
       'location', 'country', 'title_bout', 'weight_class', 'gender',
       'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak',
       'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT',
       'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses',
       'B_total_rounds_fought', 'B_total_title_bouts',
       'B_win_by_Decision_Majority', 'B_win_by_Decision_Split',
       'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission',
       'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms',
       'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak',
       'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed',
       'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct',
       'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought',
       'R_total_title_bouts', 'R_win_by_Decision_Majority',
       'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous',
       'R_win_by_KO/TKO', 'R_win_by_Submission',
       'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms',
       'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif',
       'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif',
       'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif',
       'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif',
       'avg_td_dif', 'empty_arena', 'B_match_weightclass_rank', 'R_match_weightclass_rank', 
        "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank",
        "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 
        'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 
        'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", 
        "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 
        'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 
        'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 
        'B_Pound-for-Pound_rank', 'better_rank']

In [19]:
print(test_model_name)
print(test_model)
print(test_model_features)
print(test_model_ev)

model_10
GaussianProcessClassifier(random_state=75)
[]
0

In [20]:
def save_model():
    score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)
    models[0][model_num] =  test_model_name 
    models[1][model_num] = test_model
    models[2][model_num] = test_model_features
    models[3][model_num] = test_model_ev
    models[4][model_num] = score    
    
    with open('../data/models.csv', 'w', newline='') as outfile:
        writer = csv.writer(outfile)
        for row in models:
            print("HI")
            writer.writerow(row)

    outfile.close()

In [21]:
def print_model():
    print()
    print(test_model_name)
    print(test_model)
    print(test_model_features)
    print(test_model_ev)
    print()

In [ ]:
keep_going = True
#keep_going = False
while(keep_going):
    #1. Set Features
    #get_best_features(pos_features, m, df, cur_features, labels, odds, scale=False)
    test_model_features = (get_best_features(my_pos_features, test_model, df_train, test_model_features, label_train, odds_train, 
                                             min_ev=test_model_ev))
    print_model()
    save_model()
    #2 Set hyperparameters
    #def tune_hyperparameters(input_model, input_features, input_df, input_labels, odds_input):
    test_model = tune_hyperparameters(test_model, test_model_features, df_train, label_train, odds_train, 
                                      min_ev=test_model_ev)
    print_model()
    save_model()
    #3. Set EV
    #def tune_ev(input_model, input_features, input_df, input_labels, odds_input, verbose=False):
    test_model_ev = tune_ev(test_model, test_model_features, df_train, label_train, odds_train, verbose=False)

    old_test_model_features = test_model_features #This prevents
                                                  #an uneccesary loop
    print_model()
    save_model()
    #4. Remove Features
    #def remove_to_improve(cur_features, m, df, labels, odds, scale=False, min_ev = 0):
    test_model_features = remove_to_improve(test_model_features, test_model, df_train, label_train, odds_train, min_ev = test_model_ev)    
    keep_going = False
    if old_test_model != test_model:
        print("The hyperparameters are different")
        print("OLD:")
        print(old_test_model)
        print("NEW:")
        print(test_model)
        keep_going = True
        old_test_model = test_model
    if old_test_model_features != test_model_features:
        print("The features are different")
        print("OLD:")
        print(old_test_model_features)
        print("NEW:")
        print(test_model_features)
        keep_going = True
        old_test_model_features = test_model_features
    if old_test_model_ev != test_model_ev:
        print("The EV is different")
        print("OLD:")
        print(old_test_model_ev)
        print("NEW:")
        print(test_model_ev)
        keep_going = True
        old_test_model_ev = test_model_ev
    print_model()
    save_model()

In [23]:
#Get new score:
#def evaluate_model(input_model, input_features, input_ev, train_df, train_labels, train_odds, test_df, test_labels, test_odds, verbose=True):
score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)

(3677, 17)

(3677,)

(3677, 2)

(250, 17)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0        130     -162  0.455001  0.544999       0
1        200     -265  0.489262  0.510738       1
2       -230      180  0.750963  0.249037       0
3        120     -150  0.356564  0.643436       1
4        100     -125  0.471081  0.528919       1
..       ...      ...       ...       ...     ...
245     -157      137  0.500000  0.500000       0
246     -345      285  0.777682  0.222318       0
247     -185      160  0.631030  0.368970       1
248     -160      140  0.508451  0.491549       0
249     -135      115  0.383551  0.616449       0

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 209
          Number of winning bets: 102
          Number of losing bets: 109
          Number of underdog bets: 131
          Number of underdog wins: 53
          Number of underdog losses: 78
          Number of Favorite bets: 77
          Number of favorite wins: 47
          Number of favorite losses: 30
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -145.18464448595918
          Profit per bet: -0.6946633707462162
          Profit per match: -0.5807385779438368

print(test_model_name) 
print(models[0][model_num])
print()
print(test_model)
print(eval(models[1][model_num]))
print()
print(test_model_features) 
print(eval(models[2][model_num]))
print()
print(test_model_ev)
print(eval(models[3][model_num]))

In [24]:
models[0][model_num] =  test_model_name 
models[1][model_num] = test_model
models[2][model_num] = test_model_features
models[3][model_num] = test_model_ev
models[4][model_num] = score

In [25]:
with open('../data/models.csv', 'w', newline='') as outfile:
    writer = csv.writer(outfile)
    for row in models:
        print("HI")
        writer.writerow(row)
    
outfile.close()

HI
HI
HI
HI
HI

In [26]:
with open('../data/models.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
    
print(len(data))

5

In [27]:
data

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_5',
  'model_6',
  'model_7',
  'model_8',
  'model_9',
  'model_10'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(criterion='entropy', max_depth=10, max_leaf_nodes=336,\n                       min_samples_leaf=0.01, random_state=75,\n                       splitter='random')",
  "RandomForestClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,\n                       min_samples_leaf=0.009999000000000001, n_estimators=140,\n                       n_jobs=-1, random_state=75)",
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=0.0015,\n                           n_estimators=195, random_state=75)',
  'GaussianNB()',
  "ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,\n                    min_samples_leaf=0.009999000000000001, random_state=75)",
  'MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)',
  "RadiusNeighborsClassifier(outlier_label='most_frequent')",
  'KNeighborsClassifier()',
  "SGDClassifier(loss='modified_huber', random_state=75)",
  'GaussianProcessClassifier(random_state=75)'],
 ["['R_age', 'R_draw', 'B_losses', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'age_dif', 'B_ev', 'empty_arena']",
  "['weight_class', 'R_odds', 'location', 'empty_arena']",
  "['no_of_rounds', 'B_draw', 'country', 'B_ev', 'R_Height_cms', 'B_odds', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']",
  '["R_Women\'s Featherweight_rank", \'B_Featherweight_rank\', \'B_win_by_KO/TKO\', \'R_Pound-for-Pound_rank\', \'reach_dif\', "R_Women\'s Bantamweight_rank", \'age_dif\', \'weight_class\', \'B_Reach_cms\', \'B_Welterweight_rank\', \'B_total_title_bouts\', \'R_avg_TD_pct\', \'B_Bantamweight_rank\', \'R_Featherweight_rank\', \'no_of_rounds\', \'B_draw\', \'B_Stance\', \'R_win_by_TKO_Doctor_Stoppage\', \'R_current_win_streak\', \'B_avg_SIG_STR_landed\', \'country\']',
  "['B_win_by_Decision_Unanimous', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_ev', 'B_avg_TD_landed']",
  "['R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'B_ev']",
  '[\'R_draw\', \'B_Lightweight_rank\', \'R_Lightweight_rank\', "R_Women\'s Strawweight_rank", \'B_Flyweight_rank\', \'B_draw\', \'R_win_by_Decision_Majority\', \'R_Flyweight_rank\', \'height_dif\', \'B_total_title_bouts\', \'B_Bantamweight_rank\', \'total_title_bout_dif\', \'R_longest_win_streak\', \'R_avg_TD_landed\', \'B_avg_SIG_STR_landed\']',
  "['R_win_by_KO/TKO']",
  '["B_Women\'s Strawweight_rank", \'R_avg_TD_pct\', \'B_ev\']',
  '["B_Women\'s Bantamweight_rank", \'B_Welterweight_rank\', \'R_Middleweight_rank\', "R_Women\'s Flyweight_rank", \'B_Light Heavyweight_rank\', \'B_Middleweight_rank\', \'R_Welterweight_rank\', \'avg_sub_att_dif\', "R_Women\'s Bantamweight_rank", \'B_Lightweight_rank\', \'B_ev\', "B_Women\'s Flyweight_rank", \'B_draw\', \'B_avg_SUB_ATT\', \'R_age\', \'loss_dif\', \'R_ev\']'],
 ['0', '0', '0', '33', '0', '6', '1', '1', '1', '0', '0'],
 ['756.4408141',
  '454.1692746',
  '-290.9255036',
  '2770.653314',
  '1103.751827',
  '-223.1757086',
  '927.5219432',
  '895.4540868',
  '-1524.7893',
  '2083.539134',
  '-145.18464448595918']]