In [1]:
import pandas as pd
import numpy as np
from functions import *
import random
import csv
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier

remove_fight_island = True

In [2]:
#Load models
#REMINDER: We are going to need to use 'eval' to get the models usable
with open('models.csv', newline='') as f:
    reader = csv.reader(f)
    models = list(reader)
    
print(len(models))


###SELECT MODEL TO OPTIMIZE
model_num = 4

5

In [3]:
models

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_06_13_20',
  'model_06_20_20',
  'model_6_27_20',
  'model_7_18_20',
  'model_7_25_20',
  'model_9_2_20',
  'model_9_10_20',
  'model_10_23_20',
  'model_10_27_20',
  'model_10_28_20'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(max_depth=27, max_leaf_nodes=336, min_samples_leaf=3,\n                       random_state=75, splitter='random')",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)",
  "GradientBoostingClassifier(max_depth=17, max_features='sqrt',\n                           max_leaf_nodes=316, min_samples_leaf=6,\n                           n_estimators=195, random_state=75)",
  'GaussianNB(var_smoothing=1e-08)',
  'LogisticRegression(max_iter=50000, random_state=75, tol=5.993308915320019)',
  'GaussianNB()',
  'GaussianNB()',
  'GradientBoostingClassifier(n_estimators=122, random_state=75)',
  'GaussianNB()',
  'GaussianNB(var_smoothing=1e-12)',
  'GaussianNB(var_smoothing=1e-12)',
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=6, n_estimators=195,\n                           random_state=75)',
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=197,\n                       n_jobs=-1, random_state=75)",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)"],
 ['[\'R_Welterweight_rank\', \'R_Middleweight_rank\', \'B_Light Heavyweight_rank\', \'R_draw\', \'R_win_by_Decision_Majority\', \'sig_str_dif\', \'B_Featherweight_rank\', \'R_Lightweight_rank\', \'B_odds\', \'R_avg_TD_landed\', \'B_ev\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\']',
  '[\'longest_win_streak_dif\', \'avg_td_dif\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'R_Stance\', \'R_avg_SUB_ATT\', \'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '["B_Women\'s Bantamweight_rank", "R_Women\'s Flyweight_rank", \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\']',
  "['B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']",
  "['B_win_by_Decision_Majority', 'B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'R_odds', 'R_current_lose_streak', 'R_Reach_cms', 'B_draw', 'total_round_dif', 'R_ev', 'B_ev']",
  "['R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_current_win_streak', 'R_win_by_Submission', 'B_win_by_Decision_Unanimous', 'R_win_by_Decision_Unanimous', 'R_current_lose_streak', 'B_win_by_TKO_Doctor_Stoppage', 'win_dif', 'B_win_by_Decision_Split', 'B_wins', 'R_Stance', 'B_age', 'B_Weight_lbs', 'R_ev', 'B_total_rounds_fought', 'location', 'R_odds', 'R_Reach_cms', 'R_Weight_lbs', 'R_current_win_streak', 'R_age', 'empty_arena', 'R_win_by_Decision_Split', 'R_draw', 'lose_streak_dif', 'B_draw']",
  "['R_Reach_cms', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'ko_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['win_streak_dif', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['B_Weight_lbs', 'B_Flyweight_rank', 'B_avg_TD_landed', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']",
  '[\'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']'],
 ['0', '0', '4', '35', '0', '0', '0', '0', '0', '1', '3', '2', '27', '1', '5'],
 ['-177.3976305032445',
  '-517.5586724157288',
  '51.485661931175315',
  '-273.34880970516065',
  '578.1388073',
  '-708.2060686',
  '509.4118744',
  '1122.644041',
  '-12.87052008',
  '642.8135906',
  '203.2974615',
  '179.6331948',
  '601.1884794',
  '1255.868899',
  '214.6801635']]

In [4]:
df = pd.read_csv("../data/ufc-master.csv")

In [5]:
#Let's put all the labels in a dataframe
df['label'] = ''
#If the winner is not Red or Blue we can remove it.
mask = df['Winner'] == 'Red'
df['label'][mask] = 0
mask = df['Winner'] == 'Blue'
df['label'][mask] = 1

#df["Winner"] = df["Winner"].astype('category')
df = df[(df['Winner'] == 'Blue') | (df['Winner'] == 'Red')]


#Make sure lable is numeric
df['label'] = pd.to_numeric(df['label'], errors='coerce')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [6]:
#Let's fix the date
df['date'] = pd.to_datetime(df['date'])

In [7]:
#Create a label df:
label_df = df['label']

#Let's create an odds df too:
odds_df = df[['R_odds', 'B_odds']]

In [8]:
#Split the test set.  We are always(?) going to use the last 200 matches as the test set, so we don't want those around
#as we pick models

df_train = df[200:]
odds_train = odds_df[200:]
label_train = label_df[200:]

df_test = df[:200]
odds_test = odds_df[:200]
label_test = label_df[:200]

print(len(df_test))
print(len(odds_test))
print(len(label_test))

print(len(df_train))
print(len(odds_train))
print(len(label_train))

200
200
200
4264
4264
4264

In [9]:
if remove_fight_island:
    ##Let's remove the Fight island contests and see how that affects score
    df_test_no_fight_island = df_test[(df_test['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_train_no_fight_island = df_train[(df_train['location'] != 'Abu Dhabi, Abu Dhabi, United Arab Emirates')]
    df_test = df_test_no_fight_island
    df_train = df_train_no_fight_island



print(len(df_test))
print(len(df_train))

101
4244

In [10]:
display(df_train)
display(df_test)

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
208,Dustin Poirier,Dan Hooker,-225,180,44.444444,180.000000,2020-06-27,"Las Vegas, Nevada, USA",USA,Red,...,9.0,0.14,0.44,4.0,0.0,1.0,0.0,0.0,0.0,0
209,Mike Perry,Mickey Gall,-315,235,31.746032,235.000000,2020-06-27,"Las Vegas, Nevada, USA",USA,Red,...,6.0,1.00,0.00,0.0,0.0,6.0,0.0,0.0,1.0,0
210,Brendan Allen,Kyle Daukaus,-305,235,32.786885,235.000000,2020-06-27,"Las Vegas, Nevada, USA",USA,Red,...,5.0,0.00,0.60,0.0,0.0,4.0,4.0,4.0,1.0,0
211,Gian Villante,Maurice Greene,180,-230,180.000000,43.478261,2020-06-27,"Las Vegas, Nevada, USA",USA,Blue,...,0.0,0.00,0.00,0.0,1.0,1.0,0.0,0.0,0.0,1
212,Luis Pena,Khama Worthy,-250,195,40.000000,195.000000,2020-06-27,"Las Vegas, Nevada, USA",USA,Blue,...,0.0,0.42,0.00,3.0,1.0,6.0,0.0,0.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4459,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,2.0,0.00,0.50,0.0,0.0,0.0,0.0,0.0,0.0,1
4460,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,1.00,1.00,0.0,1.0,0.0,1.0,0.0,1.0,0
4461,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,2.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0
4462,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,0.0,0.60,0.00,0.0,0.0,6.0,0.0,0.0,0.0,0
4463,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,6.0,0.66,0.50,1.0,1.0,1.0,6.0,1.0,1.0,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Thiago Santos,Glover Teixeira,-240,190,41.666667,190.000000,2020-11-07,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,Andrei Arlovski,Tanner Boser,235,-305,235.000000,32.786885,2020-11-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Raoni Barcelos,Khalid Taha,-400,295,25.000000,295.000000,2020-11-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Claudia Gadelha,Yan Xiaonan,125,-155,125.000000,64.516129,2020-11-07,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Trevin Giles,Bevon Lewis,100,-125,100.000000,80.000000,2020-11-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Vicente Luque,Randy Brown,-200,160,50.000000,160.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
153,Lando Vannata,Bobby Green,-162,130,61.728395,130.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
154,Frankie Saenz,Jonathan Martinez,200,-250,200.000000,40.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
155,Johnny Munoz,Nate Maness,110,-137,110.000000,72.992701,2020-08-01,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
156,Jamall Emmers,Vince Cachero,-360,265,27.777778,265.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [11]:
#Set a value for the nulls in the ranks

weightclass_list = ['B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank']
df_train[weightclass_list] = df_train[weightclass_list].fillna(17)
df_test[weightclass_list] = df_test[weightclass_list].fillna(17)

In [12]:
df_test
#df_test.to_csv('test.csv')

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_td_attempted_bout,R_td_pct_bout,B_td_pct_bout,R_sub_attempts_bout,B_sub_attempts_bout,R_pass_bout,B_pass_bout,R_rev_bout,B_rev_bout,label
0,Thiago Santos,Glover Teixeira,-240,190,41.666667,190.000000,2020-11-07,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,Andrei Arlovski,Tanner Boser,235,-305,235.000000,32.786885,2020-11-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Raoni Barcelos,Khalid Taha,-400,295,25.000000,295.000000,2020-11-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Claudia Gadelha,Yan Xiaonan,125,-155,125.000000,64.516129,2020-11-07,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Trevin Giles,Bevon Lewis,100,-125,100.000000,80.000000,2020-11-07,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Vicente Luque,Randy Brown,-200,160,50.000000,160.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
153,Lando Vannata,Bobby Green,-162,130,61.728395,130.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
154,Frankie Saenz,Jonathan Martinez,200,-250,200.000000,40.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
155,Johnny Munoz,Nate Maness,110,-137,110.000000,72.992701,2020-08-01,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
156,Jamall Emmers,Vince Cachero,-360,265,27.777778,265.000000,2020-08-01,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
#1. Set features
#2. Set Hyperparameters
#3. Set EV
#4. Remove Features

In [14]:
models[1][model_num]

'GaussianNB(var_smoothing=1e-08)'

In [15]:
test_model_name = models[0][model_num]
test_model = eval(models[1][model_num])
test_model_features = eval(models[2][model_num])
test_model_ev = eval(models[3][model_num])

In [16]:
old_test_model = test_model
old_test_model_features = test_model_features
old_test_model_ev = test_model_ev

In [17]:
print(df_test.columns.tolist()) #Keeps us from truncating

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'R_kd_bout', 'B_kd_bout', 'R_sig_str_landed_bout', 'B_sig_str_landed_bout', 'R_sig_str_attempted_bout', 'B_sig_str_attempted_bout', 'R_sig_str_pct_bout', 'B_sig_str_pct_bout', 'R_tot_str_landed_bout', 'B_tot_str_landed_bout', 'R_tot_str_attempted_bout', 'B_tot_str_attempted_bout', 'R_td_landed_bout', 'B_td_landed_bout', 'R_td_attempted_bout', 'B_td_attempted_bout', 'R_td_pct_bout', 'B_td_pct_bout', 'R_sub_attempts_bout', 'B_sub_attempts_bout', 'R_pass_bout', 'B_pass_bout', 'R_rev_bout', 'B_rev_bout', 'label']

In [18]:
#1. set features
my_pos_features = ['R_odds', 'B_odds', 'R_ev', 'B_ev',
       'location', 'country', 'title_bout', 'weight_class', 'gender',
       'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak',
       'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT',
       'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses',
       'B_total_rounds_fought', 'B_total_title_bouts',
       'B_win_by_Decision_Majority', 'B_win_by_Decision_Split',
       'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission',
       'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms',
       'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak',
       'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed',
       'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct',
       'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought',
       'R_total_title_bouts', 'R_win_by_Decision_Majority',
       'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous',
       'R_win_by_KO/TKO', 'R_win_by_Submission',
       'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms',
       'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif',
       'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif',
       'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif',
       'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif',
       'avg_td_dif', 'empty_arena', 'B_match_weightclass_rank', 'R_match_weightclass_rank', 
        "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank",
        "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 
        'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 
        'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", 
        "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 
        'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 
        'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 
        'B_Pound-for-Pound_rank', 'better_rank']

In [19]:
print(test_model_name)
print(test_model)
print(test_model_features)
print(test_model_ev)

model_4
GaussianNB(var_smoothing=1e-08)
['B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
0

In [20]:
def save_model():
    score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)
    models[0][model_num] =  test_model_name 
    models[1][model_num] = test_model
    models[2][model_num] = test_model_features
    models[3][model_num] = test_model_ev
    models[4][model_num] = score    
    
    with open('models.csv', 'w', newline='') as outfile:
        writer = csv.writer(outfile)
        for row in models:
            print("HI")
            writer.writerow(row)

    outfile.close()

In [21]:
def print_model():
    print()
    print(test_model_name)
    print(test_model)
    print(test_model_features)
    print(test_model_ev)
    print()

In [22]:
keep_going = True
#keep_going = False
while(keep_going):
    #1. Set Features
    #get_best_features(pos_features, m, df, cur_features, labels, odds, scale=False)
    test_model_features = (get_best_features(my_pos_features, test_model, df_train, test_model_features, label_train, odds_train, 
                                             min_ev=test_model_ev))
    print_model()
    save_model()
    #2 Set hyperparameters
    #def tune_hyperparameters(input_model, input_features, input_df, input_labels, odds_input):
    test_model = tune_hyperparameters(test_model, test_model_features, df_train, label_train, odds_train, 
                                      min_ev=test_model_ev)
    print_model()
    save_model()
    #3. Set EV
    #def tune_ev(input_model, input_features, input_df, input_labels, odds_input, verbose=False):
    test_model_ev = tune_ev(test_model, test_model_features, df_train, label_train, odds_train, verbose=False)

    old_test_model_features = test_model_features #This prevents
                                                  #an uneccesary loop
    print_model()
    save_model()
    #4. Remove Features
    #def remove_to_improve(cur_features, m, df, labels, odds, scale=False, min_ev = 0):
    test_model_features = remove_to_improve(test_model_features, test_model, df_train, label_train, odds_train, min_ev = test_model_ev)    
    keep_going = False
    if old_test_model != test_model:
        print("The hyperparameters are different")
        print("OLD:")
        print(old_test_model)
        print("NEW:")
        print(test_model)
        keep_going = True
        old_test_model = test_model
    if old_test_model_features != test_model_features:
        print("The features are different")
        print("OLD:")
        print(old_test_model_features)
        print("NEW:")
        print(test_model_features)
        keep_going = True
        old_test_model_features = test_model_features
    if old_test_model_ev != test_model_ev:
        print("The EV is different")
        print("OLD:")
        print(old_test_model_ev)
        print("NEW:")
        print(test_model_ev)
        keep_going = True
        old_test_model_ev = test_model_ev
    print_model()
    save_model()

Current best score is: 13328.77505252174
Feature: R_odds Score: 14742.463970056659
Feature: B_odds Score: 18749.14445277088
The best feature was B_odds.  It scored 18749.14445277088
Current best score is: 18749.14445277088
Feature: B_current_win_streak Score: 19139.91449585112
Feature: B_draw Score: 21384.35455513188
The best feature was B_draw.  It scored 21384.35455513188
Current best score is: 21384.35455513188
Feature: B_current_win_streak Score: 21929.47769380241
Feature: lose_streak_dif Score: 22007.525520883064
The best feature was lose_streak_dif.  It scored 22007.525520883064
Current best score is: 22007.525520883064
Feature: B_current_win_streak Score: 22602.222235846006
Feature: age_dif Score: 23238.98935726594
The best feature was age_dif.  It scored 23238.98935726594
Current best score is: 23238.98935726594
Feature: reach_dif Score: 24092.8624107007
The best feature was reach_dif.  It scored 24092.8624107007
Current best score is: 24092.8624107007
Feature: B_avg_SIG_STR_pct Score: 24466.26176806947
Feature: B_Weight_lbs Score: 24701.719931095886
Feature: R_Height_cms Score: 25757.773203380435
The best feature was R_Height_cms.  It scored 25757.773203380435
Current best score is: 25757.773203380435
NO IMPROVEMENT
FINAL BEST SCORE: 25757.773203380435

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
0

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI


Starting New Run for GaussianNB


Previous Best Score: 25757.773203380435
var_smoothing: 1e-12 Score: 13452.95328838773
var_smoothing: 1e-11 Score: 15201.43426504658
var_smoothing: 1e-10 Score: 16480.00040569956
var_smoothing: 1e-09 Score: 19841.014453447304
var_smoothing: 1e-08 Score: 25757.773203380435
var_smoothing: 1e-07 Score: 16590.544254351476
var_smoothing: 1e-06 Score: 6366.991714485844

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
0

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI
0 25757.773203380435
1 26020.7490345591
2 24884.640694810587
3 23704.753967292705
4 23470.626876468068
5 23094.640475447464
6 22593.414025494287
7 22376.864021159916
8 22358.340928323367
9 21961.21064507106
10 21725.814151360853
11 21590.830973946544
12 20959.98631961937
13 20444.117163941548
14 19952.40237527452
15 19131.801623205207
16 19463.546154372136
17 19162.723960920885
18 18254.113657686074
19 18158.870284143642
20 17877.190680540818
21 18326.055827495147
22 19077.12092794077
23 17595.356630918483
24 16976.916496064903
25 16894.702490917578
26 17234.576211062347
27 16920.958134186043
28 16536.16675697089
29 17729.49826274677
30 17458.802814180024
31 18156.344290880214
32 17622.12398502549
33 16790.873529886303
34 16946.471944172255
35 16605.75686982924
36 17108.65191446782
37 16786.815376114024
38 15989.519743388963
39 16827.186508394152
40 15576.694644758305
41 15023.003807591032
42 14169.65097091608
43 13952.763229987804
44 14501.524819547349
45 14250.813997783072
46 14285.593942214968
47 13743.835938299006
48 13570.608245465175
49 13644.778456019347
50 14001.609498334255
51 13845.494417991122
52 14322.671273076321
53 14249.207557046819
54 14368.662518053503
55 14221.498926293452
56 14739.446274959966
57 15304.489543050902
58 14610.256724286723
59 14959.918043359809
60 15012.810232559554
61 14867.55265680198
62 14802.652140586597
63 14552.758051916644
64 14253.181332339926
65 13551.34803771464
66 13418.534184900785
67 14043.772280138883
68 13604.516907825036
69 12728.191784672328
70 12457.525422479248
71 12120.38108533491
72 12937.047752001577
73 12048.89960385343
74 11267.603307557132
75 10752.726557897775
76 10532.726557897775
77 10287.168637557246
78 10583.255594078986
79 10933.255594078986
80 10513.255594078986
81 10683.255594078986
82 10699.331859225102
83 11072.375337485972
84 11788.571918682552
85 11259.658875204292
86 11692.658875204292
87 11918.745831726032
88 11703.745831726032
89 11682.83674081694
90 11626.92764990785
91 11724.200377180576
92 11686.96228194248
93 11421.724186704385
94 10741.48609146629
95 10556.48609146629
96 10281.009900990099
97 10002.009900990099
98 10447.009900990099
99 10647.009900990099
100 10230.0
101 10310.0
102 10345.0
103 10045.0
104 10745.0
105 10320.0
106 10520.0
107 10685.0
108 10875.0
109 11145.0
110 10694.0
111 10084.0
112 9750.0
113 9795.0
114 10295.0
115 10000.0
116 10100.0
117 10300.0
118 10305.0
119 10230.0
120 9390.0
121 9490.0
122 9475.0
123 9422.0
124 8907.0
125 8607.0
126 8492.0
127 8202.0
128 7842.0
129 7667.0
130 7707.0
131 7612.0
132 7712.0
133 7257.0
134 7457.0
135 7552.0
136 7557.0
137 7357.0
138 6564.0
139 6574.0
140 6369.0
141 6569.0
142 6481.0
143 6356.0
144 6288.0
145 5883.0
146 6083.0
147 6283.0
148 6383.0
149 6308.0
150 6558.0
151 6256.0
152 6356.0
153 6186.0
154 6286.0
155 6276.0
156 6341.0
157 6441.0
158 5681.0
159 5881.0
160 6181.0
161 5971.0
162 5971.0
163 5971.0
164 5971.0
165 6036.0
166 5816.0
167 5846.0
168 5651.0
169 5851.0
170 5781.0
171 5781.0
172 5781.0
173 5616.0
174 5716.0
175 5941.0
176 5941.0
177 6041.0
178 5906.0
179 5906.0
180 5738.0
181 5938.0
182 6038.0
183 5608.0
184 5708.0
185 5168.0
186 5168.0
187 5168.0
188 5273.0
189 5028.0
190 5428.0
191 5428.0
192 5528.0
193 5528.0
194 5628.0
195 5828.0
196 5563.0
197 5563.0
198 5563.0
199 5663.0

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
1

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI
The original score is 26020.7490345591
Score:  24203.71125024896
Score:  21945.741436415236
Score:  20265.598235770867
Score:  23635.8964736031
Score:  22981.9412392797
Score:  18420.01336807795
Score:  24541.287285867475
Score:  23306.911365343843
Score:  24962.404141976247
Score:  25675.041963852032
Score:  25213.826112261457
Score:  24073.47563301077
Score:  23693.232829344317
Score:  24740.017513784755
Score:  22415.084007296395
Score:  23911.009835428355
Score:  20830.144944661704
Score:  19787.097428631954
Score:  21948.963194414406
Score:  20769.741727524077
Score:  18686.69833733415
Score:  22949.122988733703
Score:  22161.23455010785
Score:  20362.86921267351
Score:  19855.024062468463
Score:  20685.270765495465
Score:  19630.372239201948
Score:  18006.56193103059
Score:  15627.887930354003
Score:  20806.2732805921
Score:  23336.36668494266
Score:  24429.636060761655
The EV is different
OLD:
0
NEW:
1

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
1

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI
Current best score is: 26020.7490345591
NO IMPROVEMENT
FINAL BEST SCORE: 26020.7490345591

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
1

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI


Starting New Run for GaussianNB


Previous Best Score: 26020.7490345591
var_smoothing: 1e-12 Score: 13222.14869068658
var_smoothing: 1e-11 Score: 15153.508455224219
var_smoothing: 1e-10 Score: 16581.1643566911
var_smoothing: 1e-09 Score: 19589.920000673694
var_smoothing: 1e-08 Score: 26020.7490345591
var_smoothing: 1e-07 Score: 16039.356367856628
var_smoothing: 1e-06 Score: 7991.988459663573

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
1

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI
0 25757.773203380435
1 26020.7490345591
2 24884.640694810587
3 23704.753967292705
4 23470.626876468068
5 23094.640475447464
6 22593.414025494287
7 22376.864021159916
8 22358.340928323367
9 21961.21064507106
10 21725.814151360853
11 21590.830973946544
12 20959.98631961937
13 20444.117163941548
14 19952.40237527452
15 19131.801623205207
16 19463.546154372136
17 19162.723960920885
18 18254.113657686074
19 18158.870284143642
20 17877.190680540818
21 18326.055827495147
22 19077.12092794077
23 17595.356630918483
24 16976.916496064903
25 16894.702490917578
26 17234.576211062347
27 16920.958134186043
28 16536.16675697089
29 17729.49826274677
30 17458.802814180024
31 18156.344290880214
32 17622.12398502549
33 16790.873529886303
34 16946.471944172255
35 16605.75686982924
36 17108.65191446782
37 16786.815376114024
38 15989.519743388963
39 16827.186508394152
40 15576.694644758305
41 15023.003807591032
42 14169.65097091608
43 13952.763229987804
44 14501.524819547349
45 14250.813997783072
46 14285.593942214968
47 13743.835938299006
48 13570.608245465175
49 13644.778456019347
50 14001.609498334255
51 13845.494417991122
52 14322.671273076321
53 14249.207557046819
54 14368.662518053503
55 14221.498926293452
56 14739.446274959966
57 15304.489543050902
58 14610.256724286723
59 14959.918043359809
60 15012.810232559554
61 14867.55265680198
62 14802.652140586597
63 14552.758051916644
64 14253.181332339926
65 13551.34803771464
66 13418.534184900785
67 14043.772280138883
68 13604.516907825036
69 12728.191784672328
70 12457.525422479248
71 12120.38108533491
72 12937.047752001577
73 12048.89960385343
74 11267.603307557132
75 10752.726557897775
76 10532.726557897775
77 10287.168637557246
78 10583.255594078986
79 10933.255594078986
80 10513.255594078986
81 10683.255594078986
82 10699.331859225102
83 11072.375337485972
84 11788.571918682552
85 11259.658875204292
86 11692.658875204292
87 11918.745831726032
88 11703.745831726032
89 11682.83674081694
90 11626.92764990785
91 11724.200377180576
92 11686.96228194248
93 11421.724186704385
94 10741.48609146629
95 10556.48609146629
96 10281.009900990099
97 10002.009900990099
98 10447.009900990099
99 10647.009900990099
100 10230.0
101 10310.0
102 10345.0
103 10045.0
104 10745.0
105 10320.0
106 10520.0
107 10685.0
108 10875.0
109 11145.0
110 10694.0
111 10084.0
112 9750.0
113 9795.0
114 10295.0
115 10000.0
116 10100.0
117 10300.0
118 10305.0
119 10230.0
120 9390.0
121 9490.0
122 9475.0
123 9422.0
124 8907.0
125 8607.0
126 8492.0
127 8202.0
128 7842.0
129 7667.0
130 7707.0
131 7612.0
132 7712.0
133 7257.0
134 7457.0
135 7552.0
136 7557.0
137 7357.0
138 6564.0
139 6574.0
140 6369.0
141 6569.0
142 6481.0
143 6356.0
144 6288.0
145 5883.0
146 6083.0
147 6283.0
148 6383.0
149 6308.0
150 6558.0
151 6256.0
152 6356.0
153 6186.0
154 6286.0
155 6276.0
156 6341.0
157 6441.0
158 5681.0
159 5881.0
160 6181.0
161 5971.0
162 5971.0
163 5971.0
164 5971.0
165 6036.0
166 5816.0
167 5846.0
168 5651.0
169 5851.0
170 5781.0
171 5781.0
172 5781.0
173 5616.0
174 5716.0
175 5941.0
176 5941.0
177 6041.0
178 5906.0
179 5906.0
180 5738.0
181 5938.0
182 6038.0
183 5608.0
184 5708.0
185 5168.0
186 5168.0
187 5168.0
188 5273.0
189 5028.0
190 5428.0
191 5428.0
192 5528.0
193 5528.0
194 5628.0
195 5828.0
196 5563.0
197 5563.0
198 5563.0
199 5663.0

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
1

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI
The original score is 26020.7490345591
Score:  24203.71125024896
Score:  21945.741436415236
Score:  20265.598235770867
Score:  23635.8964736031
Score:  22981.9412392797
Score:  18420.01336807795
Score:  24541.287285867475
Score:  23306.911365343843
Score:  24962.404141976247
Score:  25675.041963852032
Score:  25213.826112261457
Score:  24073.47563301077
Score:  23693.232829344317
Score:  24740.017513784755
Score:  22415.084007296395
Score:  23911.009835428355
Score:  20830.144944661704
Score:  19787.097428631954
Score:  21948.963194414406
Score:  20769.741727524077
Score:  18686.69833733415
Score:  22949.122988733703
Score:  22161.23455010785
Score:  20362.86921267351
Score:  19855.024062468463
Score:  20685.270765495465
Score:  19630.372239201948
Score:  18006.56193103059
Score:  15627.887930354003
Score:  20806.2732805921
Score:  23336.36668494266
Score:  24429.636060761655

model_4
GaussianNB(var_smoothing=1e-08)
['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']
1

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124


HI
HI
HI
HI
HI

In [23]:
#Get new score:
#def evaluate_model(input_model, input_features, input_ev, train_df, train_labels, train_odds, test_df, test_labels, test_odds, verbose=True):
score = evaluate_model(test_model, test_model_features, test_model_ev, df_train, label_train, odds_train, df_test, label_test,
                         odds_test, verbose = True)

(3203, 37)

(3203,)

(3203, 2)

(101, 37)

(101,)

(101, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -240      190  0.999774  0.000226       1
1        235     -305  0.991178  0.008822       0
2       -400      295  0.999396  0.000604       0
3        125     -155  0.991881  0.008119       1
4        100     -125  0.995784  0.004216       0
..       ...      ...       ...       ...     ...
96      -200      160  0.994273  0.005727       0
97      -162      130  0.000115  0.999885       1
98       200     -250  0.980883  0.019117       1
99       110     -137  0.971089  0.028911       1
100     -360      265  0.999092  0.000908       0

[101 rows x 5 columns]

          Number of matches: 101
          Number of bets: 101
          Number of winning bets: 64
          Number of losing bets: 37
          Number of underdog bets: 41
          Number of underdog wins: 19
          Number of underdog losses: 22
          Number of Favorite bets: 57
          Number of favorite wins: 44
          Number of favorite losses: 13
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 1182.7971751988935
          Profit per bet: 11.710863120781124
          Profit per match: 11.710863120781124

print(test_model_name) 
print(models[0][model_num])
print()
print(test_model)
print(eval(models[1][model_num]))
print()
print(test_model_features) 
print(eval(models[2][model_num]))
print()
print(test_model_ev)
print(eval(models[3][model_num]))

In [24]:
models[0][model_num] =  test_model_name 
models[1][model_num] = test_model
models[2][model_num] = test_model_features
models[3][model_num] = test_model_ev
models[4][model_num] = score

In [25]:
with open('models.csv', 'w', newline='') as outfile:
    writer = csv.writer(outfile)
    for row in models:
        print("HI")
        writer.writerow(row)
    
outfile.close()

HI
HI
HI
HI
HI

In [26]:
with open('models.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
    
print(len(data))

5

In [27]:
data

[['model_0',
  'model_1',
  'model_2',
  'model_3',
  'model_4',
  'model_06_13_20',
  'model_06_20_20',
  'model_6_27_20',
  'model_7_18_20',
  'model_7_25_20',
  'model_9_2_20',
  'model_9_10_20',
  'model_10_23_20',
  'model_10_27_20',
  'model_10_28_20'],
 ['LogisticRegression(max_iter=50000, random_state=75)',
  "DecisionTreeClassifier(max_depth=27, max_leaf_nodes=336, min_samples_leaf=3,\n                       random_state=75, splitter='random')",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)",
  "GradientBoostingClassifier(max_depth=17, max_features='sqrt',\n                           max_leaf_nodes=316, min_samples_leaf=6,\n                           n_estimators=195, random_state=75)",
  'GaussianNB(var_smoothing=1e-08)',
  'LogisticRegression(max_iter=50000, random_state=75, tol=5.993308915320019)',
  'GaussianNB()',
  'GaussianNB()',
  'GradientBoostingClassifier(n_estimators=122, random_state=75)',
  'GaussianNB()',
  'GaussianNB(var_smoothing=1e-12)',
  'GaussianNB(var_smoothing=1e-12)',
  'GradientBoostingClassifier(max_depth=95, min_samples_leaf=6, n_estimators=195,\n                           random_state=75)',
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=197,\n                       n_jobs=-1, random_state=75)",
  "RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=22,\n                       n_jobs=-1, random_state=75)"],
 ['[\'R_Welterweight_rank\', \'R_Middleweight_rank\', \'B_Light Heavyweight_rank\', \'R_draw\', \'R_win_by_Decision_Majority\', \'sig_str_dif\', \'B_Featherweight_rank\', \'R_Lightweight_rank\', \'B_odds\', \'R_avg_TD_landed\', \'B_ev\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\']',
  '[\'longest_win_streak_dif\', \'avg_td_dif\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'R_Stance\', \'R_avg_SUB_ATT\', \'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '["B_Women\'s Bantamweight_rank", "R_Women\'s Flyweight_rank", \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\']',
  "['R_Height_cms', 'reach_dif', 'age_dif', 'lose_streak_dif', 'B_draw', 'B_odds', 'B_avg_TD_pct', 'R_Reach_cms', 'B_win_by_Decision_Unanimous', 'R_win_by_Submission', 'height_dif', 'R_avg_TD_pct', 'R_avg_SIG_STR_pct', 'win_streak_dif', 'B_avg_TD_landed', 'B_current_lose_streak', 'B_age', 'R_win_by_Decision_Split', 'avg_td_dif', 'R_Middleweight_rank', 'better_rank', 'B_Flyweight_rank', 'B_win_by_KO/TKO', 'B_win_by_Decision_Split', 'R_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Flyweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'B_Stance', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed', 'empty_arena']",
  "['B_win_by_Decision_Majority', 'B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Decision_Majority', 'R_odds', 'R_current_lose_streak', 'R_Reach_cms', 'B_draw', 'total_round_dif', 'R_ev', 'B_ev']",
  "['R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'B_win_by_Submission', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['B_current_win_streak', 'R_win_by_Submission', 'B_win_by_Decision_Unanimous', 'R_win_by_Decision_Unanimous', 'R_current_lose_streak', 'B_win_by_TKO_Doctor_Stoppage', 'win_dif', 'B_win_by_Decision_Split', 'B_wins', 'R_Stance', 'B_age', 'B_Weight_lbs', 'R_ev', 'B_total_rounds_fought', 'location', 'R_odds', 'R_Reach_cms', 'R_Weight_lbs', 'R_current_win_streak', 'R_age', 'empty_arena', 'R_win_by_Decision_Split', 'R_draw', 'lose_streak_dif', 'B_draw']",
  "['R_Reach_cms', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'ko_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']",
  "['win_streak_dif', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'total_round_dif', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'R_Weight_lbs', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['B_Weight_lbs', 'B_Flyweight_rank', 'B_avg_TD_landed', 'B_Light Heavyweight_rank', 'B_Lightweight_rank', 'R_avg_TD_landed', 'R_Middleweight_rank', 'R_Height_cms', 'R_avg_SIG_STR_pct', 'B_age', 'R_longest_win_streak', 'lose_streak_dif', 'R_win_by_Decision_Majority', 'longest_win_streak_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'B_draw', 'R_win_by_Decision_Split', 'age_dif', 'R_odds']",
  "['weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']",
  '[\'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']',
  '[\'B_Stance\', \'R_current_lose_streak\', \'loss_dif\', \'B_win_by_Decision_Split\', \'R_Height_cms\', \'R_Bantamweight_rank\', \'B_current_lose_streak\', \'avg_sub_att_dif\', \'B_Middleweight_rank\', \'R_current_win_streak\', \'total_round_dif\', \'B_avg_SUB_ATT\', \'B_avg_SIG_STR_landed\', \'age_dif\', \'B_Light Heavyweight_rank\', \'R_avg_TD_pct\', \'R_ev\', "B_Women\'s Flyweight_rank", "B_Women\'s Strawweight_rank", \'B_Bantamweight_rank\', \'R_Reach_cms\', \'B_win_by_Decision_Unanimous\', \'constant_1\']'],
 ['0', '0', '4', '35', '1', '0', '0', '0', '0', '1', '3', '2', '27', '1', '5'],
 ['-177.3976305032445',
  '-517.5586724157288',
  '51.485661931175315',
  '-273.34880970516065',
  '1182.7971751988935',
  '-708.2060686',
  '509.4118744',
  '1122.644041',
  '-12.87052008',
  '642.8135906',
  '203.2974615',
  '179.6331948',
  '601.1884794',
  '1255.868899',
  '214.6801635']]